In [1]:
import pandas as pd
import openpyxl

In [2]:
xls = pd.ExcelFile("Daily Gen pdpu-From-1-01-2021 (2).xlsx")
df = pd.read_excel(xls, '2015')
df.head(20)

,Project Name,Unnamed: 1,"PDPU-SEIPL, Gujarat 2010",Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Generation of 2015,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,Project Number,NaN,IN-10-0061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Capacity,NaN,1026 KW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,PDPU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,Total Generation (KWH),Aggregate Meter Reading (KWH),Difference,SEEDs data (KWH),Insolation,PR (%),Any Issues/Problems Observed,WO#,NO-OFF-CLEAN MODULES
5,NaN,Inverter generation (KWH),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Date,1104500527,1104500529,1.104501e+09,7802195.0,2100570073/ 2100567820/ 2100567898,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2015-01-01 00:00:00,542,560,5.090000e+02,529.0,22.5,2162.5,2035.5,127,2197,2.78,77.02,Inverter No- 3 Auto trip 8:50 (modulre fan pro...,NaN,NaN
8,2015-01-02 00:00:00,792,831,8.420000e+02,821.0,36.93,3322.93,3177,145.93,3352,4.15,78.72,Grid Failure From 13:02 to 13:09 WO#3402756,NaN,NaN
9,2006-01-03 00:00:00,933,978,9.950000e+02,953.0,49.96,3908.96,3755.25,153.71,3942,5.303,72.45,Grid Failure From 8:05 to 9:19 WO#3419549,NaN,NaN
10,2015-01-04 00:00:00,1046,1102,1.114000e+03,1071.0,61.29,4394.29,4210.5,183.79,4430,NaN,NaN,Grid Failure From 16:45 to 18:45 WO#3450753,NaN,NaN
11,2015-01-05 00:00:00,893,939,9.440000e+02,902.0,41.55,3719.55,3556.5,163.05,3744,4.8,76.02,The GERMI Plant has Failure The GRID From -1...,NaN,NaN
12,2015-01-06 00:00:00,1040,1097,1.102000e+03,1065.0,58.77,4362.77,4194,168.77,4388,5.726,74.69,Today I Replaced The D.C.12Amp Fuse Link of T...,NaN,NaN
13,2015-01-07 00:00:00,543,571,5.770000e+02,551.0,29.48,2271.48,2167.5,103.98,3212,3.165,71.19,Grid Failure From 15:57 to 18:28 WO# 3518160,NaN,NaN
14,2015-01-08 00:00:00,1051,1113,1.120000e+03,1077.0,60.24,4421.24,4242.75,178.49,4444,5.805,74.61,Grid Failure From 17:42 to 18:52 WO# 3545933,NaN,NaN
15,2015-01-09 00:00:00,1092,1154,1.159000e+03,1150.0,66.91,4621.91,4439.25,182.66,4647,6.106,74.17,Battery water Fileed in 5 kw Battery Bank,NaN,NaN
16,2015-01-10 00:00:00,1079,1130,1.130000e+03,1138.0,71.79,4548.79,4379.25,169.54,4580,6.021,74.13,Grid Failure From 13:48 to 13:57 WO# 3593881,NaN,NaN
17,2015-01-11 00:00:00,1091,1137,1.154000e+03,1122.0,70.17,4574.17,4389.75,184.42,4592,6.051,73.96,NaN,NaN,NaN
18,2015-01-12 00:00:00,1041,1085,1.124000e+03,1066.0,66.71,4382.71,4197,185.71,4398,6.031,71.07,Grid Failure From 14:48 to 15:08 WO#3648062 & ...,NaN,NaN
19,2015-01-13 00:00:00,1034,1080,1.126000e+03,1048.0,60.77,4348.77,4176.75,172.02,4401,5.773,74.3,NaN,NaN,NaN

In [3]:
df = df[4:]

In [4]:
df.columns

Index(['Project Name', 'Unnamed: 1', 'PDPU-SEIPL, Gujarat 2010', 'Unnamed: 3',
       'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Generation of 2015',
       'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14'],
      dtype='object')

In [5]:
df.head(20)

,Project Name,Unnamed: 1,"PDPU-SEIPL, Gujarat 2010",Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Generation of 2015,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
4,NaN,NaN,NaN,NaN,NaN,NaN,Total Generation (KWH),Aggregate Meter Reading (KWH),Difference,SEEDs data (KWH),Insolation,PR (%),Any Issues/Problems Observed,WO#,NO-OFF-CLEAN MODULES
5,NaN,Inverter generation (KWH),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Date,1104500527,1104500529,1.104501e+09,7802195.0,2100570073/ 2100567820/ 2100567898,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2015-01-01 00:00:00,542,560,5.090000e+02,529.0,22.5,2162.5,2035.5,127,2197,2.78,77.02,Inverter No- 3 Auto trip 8:50 (modulre fan pro...,NaN,NaN
8,2015-01-02 00:00:00,792,831,8.420000e+02,821.0,36.93,3322.93,3177,145.93,3352,4.15,78.72,Grid Failure From 13:02 to 13:09 WO#3402756,NaN,NaN
9,2006-01-03 00:00:00,933,978,9.950000e+02,953.0,49.96,3908.96,3755.25,153.71,3942,5.303,72.45,Grid Failure From 8:05 to 9:19 WO#3419549,NaN,NaN
10,2015-01-04 00:00:00,1046,1102,1.114000e+03,1071.0,61.29,4394.29,4210.5,183.79,4430,NaN,NaN,Grid Failure From 16:45 to 18:45 WO#3450753,NaN,NaN
11,2015-01-05 00:00:00,893,939,9.440000e+02,902.0,41.55,3719.55,3556.5,163.05,3744,4.8,76.02,The GERMI Plant has Failure The GRID From -1...,NaN,NaN
12,2015-01-06 00:00:00,1040,1097,1.102000e+03,1065.0,58.77,4362.77,4194,168.77,4388,5.726,74.69,Today I Replaced The D.C.12Amp Fuse Link of T...,NaN,NaN
13,2015-01-07 00:00:00,543,571,5.770000e+02,551.0,29.48,2271.48,2167.5,103.98,3212,3.165,71.19,Grid Failure From 15:57 to 18:28 WO# 3518160,NaN,NaN
14,2015-01-08 00:00:00,1051,1113,1.120000e+03,1077.0,60.24,4421.24,4242.75,178.49,4444,5.805,74.61,Grid Failure From 17:42 to 18:52 WO# 3545933,NaN,NaN
15,2015-01-09 00:00:00,1092,1154,1.159000e+03,1150.0,66.91,4621.91,4439.25,182.66,4647,6.106,74.17,Battery water Fileed in 5 kw Battery Bank,NaN,NaN
16,2015-01-10 00:00:00,1079,1130,1.130000e+03,1138.0,71.79,4548.79,4379.25,169.54,4580,6.021,74.13,Grid Failure From 13:48 to 13:57 WO# 3593881,NaN,NaN
17,2015-01-11 00:00:00,1091,1137,1.154000e+03,1122.0,70.17,4574.17,4389.75,184.42,4592,6.051,73.96,NaN,NaN,NaN
18,2015-01-12 00:00:00,1041,1085,1.124000e+03,1066.0,66.71,4382.71,4197,185.71,4398,6.031,71.07,Grid Failure From 14:48 to 15:08 WO#3648062 & ...,NaN,NaN
19,2015-01-13 00:00:00,1034,1080,1.126000e+03,1048.0,60.77,4348.77,4176.75,172.02,4401,5.773,74.3,NaN,NaN,NaN
20,2015-01-14 00:00:00,786,820,8.470000e+02,772.0,37.51,3262.51,3114,148.51,3290,4.273,75.04,Cloudy day & Inverer 4 run healthy but exhaust...,NaN,NaN
21,2015-01-15 00:00:00,989,1023,1.069000e+03,966.0,54.31,4101.31,3912.75,188.56,4110,5.362,74.7,Inverter no-4 run healthy but exhaust fan not ...,NaN,NaN
22,2015-01-16 00:00:00,1040,1102,1.119000e+03,1039.0,59.66,4359.66,4181.25,178.41,4379,5.738,74.38,Grid Failure From 11:05 to 11:08 WO#3758192,NaN,NaN
23,2015-01-17 00:00:00,1143,1193,1.204000e+03,1113.0,66.42,4719.42,4523.25,196.17,4725,6.169,74.69,Grid Failure From 13:39 to 13:46 WO#3798043,NaN,NaN

In [6]:
df.columns

Index(['Project Name', 'Unnamed: 1', 'PDPU-SEIPL, Gujarat 2010', 'Unnamed: 3',
       'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Generation of 2015',
       'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14'],
      dtype='object')

In [7]:
#Unnamed: 1	PDPU-SEIPL, Gujarat 2010	Unnamed: 3	Unnamed: 4	Unnamed: 5

In [8]:
#1104500527	1104500529	1.104501e+09	7802195.0	2100570073/ 2100567820/ 2100567898

In [9]:
column_names = {"Project Name" : "Date", "Unnamed: 1" : "1104500527", "PDPU-SEIPL, Gujarat 2010" : "1104500529", 
                "Unnamed: 3" : "1.104501e+09", "Unnamed: 4" : "7802195.0", "Unnamed: 5" : "2100570073/ 2100567820/ 2100567898"}

In [10]:
df = df.rename(columns=column_names)

In [11]:
df

,Date,1104500527,1104500529,1.104501e+09,7802195.0,2100570073/ 2100567820/ 2100567898,Unnamed: 6,Generation of 2015,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
4,NaN,NaN,NaN,NaN,NaN,NaN,Total Generation (KWH),Aggregate Meter Reading (KWH),Difference,SEEDs data (KWH),Insolation,PR (%),Any Issues/Problems Observed,WO#,NO-OFF-CLEAN MODULES
5,NaN,Inverter generation (KWH),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Date,1104500527,1104500529,1.104501e+09,7802195.0,2100570073/ 2100567820/ 2100567898,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2015-01-01 00:00:00,542,560,5.090000e+02,529.0,22.5,2162.5,2035.5,127,2197,2.78,77.02,Inverter No- 3 Auto trip 8:50 (modulre fan pro...,NaN,NaN
8,2015-01-02 00:00:00,792,831,8.420000e+02,821.0,36.93,3322.93,3177,145.93,3352,4.15,78.72,Grid Failure From 13:02 to 13:09 WO#3402756,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
463,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
464,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
465,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
466,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
#Unnamed: 6	Generation of 2015	Unnamed: 8	Unnamed: 9	Unnamed: 10	Unnamed: 11	Unnamed: 12 Unnamed: 13	Unnamed: 14

In [13]:
#Total Generation (KWH)	Aggregate Meter Reading (KWH)	Difference	SEEDs data (KWH)	Insolation	PR (%)	Any Issues/Problems Observed  WO#	NO-OFF-CLEAN MODULES

In [14]:
# if int(year) < 2015

column_names = {"Unnamed: 6" : "Total Generation (KWH)", "Generation of 2015" : "Aggregate Meter Reading (KWH)",
               "Unnamed: 8" : "Difference", "Unnamed: 9" : "SEEDs data (KWH)",
               "Unnamed: 10" : "Insolation", "Unnamed: 11" : "PR (%)", "Unnamed: 12" : "Any Issues/Problems Observed",
               "Unnamed: 13" : "WO#", "Unnamed: 14" : "NO-OFF-CLEAN MODULES"}

In [15]:
df = df.rename(columns=column_names)

In [16]:
df.head(20)

,Date,1104500527,1104500529,1.104501e+09,7802195.0,2100570073/ 2100567820/ 2100567898,Total Generation (KWH),Aggregate Meter Reading (KWH),Difference,SEEDs data (KWH),Insolation,PR (%),Any Issues/Problems Observed,WO#,NO-OFF-CLEAN MODULES
4,NaN,NaN,NaN,NaN,NaN,NaN,Total Generation (KWH),Aggregate Meter Reading (KWH),Difference,SEEDs data (KWH),Insolation,PR (%),Any Issues/Problems Observed,WO#,NO-OFF-CLEAN MODULES
5,NaN,Inverter generation (KWH),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Date,1104500527,1104500529,1.104501e+09,7802195.0,2100570073/ 2100567820/ 2100567898,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2015-01-01 00:00:00,542,560,5.090000e+02,529.0,22.5,2162.5,2035.5,127,2197,2.78,77.02,Inverter No- 3 Auto trip 8:50 (modulre fan pro...,NaN,NaN
8,2015-01-02 00:00:00,792,831,8.420000e+02,821.0,36.93,3322.93,3177,145.93,3352,4.15,78.72,Grid Failure From 13:02 to 13:09 WO#3402756,NaN,NaN
9,2006-01-03 00:00:00,933,978,9.950000e+02,953.0,49.96,3908.96,3755.25,153.71,3942,5.303,72.45,Grid Failure From 8:05 to 9:19 WO#3419549,NaN,NaN
10,2015-01-04 00:00:00,1046,1102,1.114000e+03,1071.0,61.29,4394.29,4210.5,183.79,4430,NaN,NaN,Grid Failure From 16:45 to 18:45 WO#3450753,NaN,NaN
11,2015-01-05 00:00:00,893,939,9.440000e+02,902.0,41.55,3719.55,3556.5,163.05,3744,4.8,76.02,The GERMI Plant has Failure The GRID From -1...,NaN,NaN
12,2015-01-06 00:00:00,1040,1097,1.102000e+03,1065.0,58.77,4362.77,4194,168.77,4388,5.726,74.69,Today I Replaced The D.C.12Amp Fuse Link of T...,NaN,NaN
13,2015-01-07 00:00:00,543,571,5.770000e+02,551.0,29.48,2271.48,2167.5,103.98,3212,3.165,71.19,Grid Failure From 15:57 to 18:28 WO# 3518160,NaN,NaN
14,2015-01-08 00:00:00,1051,1113,1.120000e+03,1077.0,60.24,4421.24,4242.75,178.49,4444,5.805,74.61,Grid Failure From 17:42 to 18:52 WO# 3545933,NaN,NaN
15,2015-01-09 00:00:00,1092,1154,1.159000e+03,1150.0,66.91,4621.91,4439.25,182.66,4647,6.106,74.17,Battery water Fileed in 5 kw Battery Bank,NaN,NaN
16,2015-01-10 00:00:00,1079,1130,1.130000e+03,1138.0,71.79,4548.79,4379.25,169.54,4580,6.021,74.13,Grid Failure From 13:48 to 13:57 WO# 3593881,NaN,NaN
17,2015-01-11 00:00:00,1091,1137,1.154000e+03,1122.0,70.17,4574.17,4389.75,184.42,4592,6.051,73.96,NaN,NaN,NaN
18,2015-01-12 00:00:00,1041,1085,1.124000e+03,1066.0,66.71,4382.71,4197,185.71,4398,6.031,71.07,Grid Failure From 14:48 to 15:08 WO#3648062 & ...,NaN,NaN
19,2015-01-13 00:00:00,1034,1080,1.126000e+03,1048.0,60.77,4348.77,4176.75,172.02,4401,5.773,74.3,NaN,NaN,NaN
20,2015-01-14 00:00:00,786,820,8.470000e+02,772.0,37.51,3262.51,3114,148.51,3290,4.273,75.04,Cloudy day & Inverer 4 run healthy but exhaust...,NaN,NaN
21,2015-01-15 00:00:00,989,1023,1.069000e+03,966.0,54.31,4101.31,3912.75,188.56,4110,5.362,74.7,Inverter no-4 run healthy but exhaust fan not ...,NaN,NaN
22,2015-01-16 00:00:00,1040,1102,1.119000e+03,1039.0,59.66,4359.66,4181.25,178.41,4379,5.738,74.38,Grid Failure From 11:05 to 11:08 WO#3758192,NaN,NaN
23,2015-01-17 00:00:00,1143,1193,1.204000e+03,1113.0,66.42,4719.42,4523.25,196.17,4725,6.169,74.69,Grid Failure From 13:39 to 13:46 WO#3798043,NaN,NaN

In [17]:
df = df[3:]

In [18]:
df.head(10)

,Date,1104500527,1104500529,1.104501e+09,7802195.0,2100570073/ 2100567820/ 2100567898,Total Generation (KWH),Aggregate Meter Reading (KWH),Difference,SEEDs data (KWH),Insolation,PR (%),Any Issues/Problems Observed,WO#,NO-OFF-CLEAN MODULES
7,2015-01-01 00:00:00,542,560,509.0,529.0,22.5,2162.5,2035.5,127,2197,2.78,77.02,Inverter No- 3 Auto trip 8:50 (modulre fan pro...,NaN,NaN
8,2015-01-02 00:00:00,792,831,842.0,821.0,36.93,3322.93,3177,145.93,3352,4.15,78.72,Grid Failure From 13:02 to 13:09 WO#3402756,NaN,NaN
9,2006-01-03 00:00:00,933,978,995.0,953.0,49.96,3908.96,3755.25,153.71,3942,5.303,72.45,Grid Failure From 8:05 to 9:19 WO#3419549,NaN,NaN
10,2015-01-04 00:00:00,1046,1102,1114.0,1071.0,61.29,4394.29,4210.5,183.79,4430,NaN,NaN,Grid Failure From 16:45 to 18:45 WO#3450753,NaN,NaN
11,2015-01-05 00:00:00,893,939,944.0,902.0,41.55,3719.55,3556.5,163.05,3744,4.8,76.02,The GERMI Plant has Failure The GRID From -1...,NaN,NaN
12,2015-01-06 00:00:00,1040,1097,1102.0,1065.0,58.77,4362.77,4194,168.77,4388,5.726,74.69,Today I Replaced The D.C.12Amp Fuse Link of T...,NaN,NaN
13,2015-01-07 00:00:00,543,571,577.0,551.0,29.48,2271.48,2167.5,103.98,3212,3.165,71.19,Grid Failure From 15:57 to 18:28 WO# 3518160,NaN,NaN
14,2015-01-08 00:00:00,1051,1113,1120.0,1077.0,60.24,4421.24,4242.75,178.49,4444,5.805,74.61,Grid Failure From 17:42 to 18:52 WO# 3545933,NaN,NaN
15,2015-01-09 00:00:00,1092,1154,1159.0,1150.0,66.91,4621.91,4439.25,182.66,4647,6.106,74.17,Battery water Fileed in 5 kw Battery Bank,NaN,NaN
16,2015-01-10 00:00:00,1079,1130,1130.0,1138.0,71.79,4548.79,4379.25,169.54,4580,6.021,74.13,Grid Failure From 13:48 to 13:57 WO# 3593881,NaN,NaN

In [19]:
label_dict = {
    "Grid Failure" : [["Grid","Grid supply failure"], []],
    "Inverter" : [["Inverter"], ["Module Cleaning"]],
    "Module Cleaning" : [["Module Cleaning"], []],
    "Rainy day" : [["Rainy day"], []] ,
    "No Module Cleaning" : [["No Module Cleaning"], []] ,
    "MCB Replacement" : [["MCB Replacement"], []] ,
    "Inverter Maintenance" : [["Inverter Maintenance"], []] ,
    "Transformer replacement and maintenance" : [["Transformer replacement and maintenance"], []] ,
    "Cable and Fuse maintenance" : [["Cable and Fuse maintenance"], []] ,
    "Plant Shutdown" : [["Plant Shutdown"], []] ,
    "Internet" : [["Internet"], []] ,
    "Battery" : [["Battery"], []] ,
    "Cloudy" : [["Cloudy"], []] ,
    "Module Cleaning by rains" : [["Module Cleaning by rains"], []]
}
label_dict

{'Grid Failure': [['Grid', 'Grid supply failure'], []],
 'Inverter': [['Inverter'], ['Module Cleaning']],
 'Module Cleaning': [['Module Cleaning'], []],
 'Rainy day': [['Rainy day'], []],
 'No Module Cleaning': [['No Module Cleaning'], []],
 'MCB Replacement': [['MCB Replacement'], []],
 'Inverter Maintenance': [['Inverter Maintenance'], []],
 'Transformer replacement and maintenance': [['Transformer replacement and maintenance'],
  []],
 'Cable and Fuse maintenance': [['Cable and Fuse maintenance'], []],
 'Plant Shutdown': [['Plant Shutdown'], []],
 'Internet': [['Internet'], []],
 'Battery': [['Battery'], []],
 'Cloudy': [['Cloudy'], []],
 'Module Cleaning by rains': [['Module Cleaning by rains'], []]}

In [20]:
label_list = ["Grid" ,
"Module Cleaning",
"Rainy day",
"No Module Cleaning",
"MCB Replacement",
"Inverter Maintenance",
"Transformer replacement and maintenance",
"Cable and Fuse maintenance",
"Plant Shutdown",
"Inverter",
"Internet",
"Battery",
"Cloudy",
"Module Cleaning by rains",]
label_list

['Grid',
 'Module Cleaning',
 'Rainy day',
 'No Module Cleaning',
 'MCB Replacement',
 'Inverter Maintenance',
 'Transformer replacement and maintenance',
 'Cable and Fuse maintenance',
 'Plant Shutdown',
 'Inverter',
 'Internet',
 'Battery',
 'Cloudy',
 'Module Cleaning by rains']

In [21]:
df_test = df.copy()

In [22]:
#df_test.loc()

In [23]:
df_test

,Date,1104500527,1104500529,1.104501e+09,7802195.0,2100570073/ 2100567820/ 2100567898,Total Generation (KWH),Aggregate Meter Reading (KWH),Difference,SEEDs data (KWH),Insolation,PR (%),Any Issues/Problems Observed,WO#,NO-OFF-CLEAN MODULES
7,2015-01-01 00:00:00,542,560,509.0,529.0,22.5,2162.5,2035.5,127,2197,2.78,77.02,Inverter No- 3 Auto trip 8:50 (modulre fan pro...,NaN,NaN
8,2015-01-02 00:00:00,792,831,842.0,821.0,36.93,3322.93,3177,145.93,3352,4.15,78.72,Grid Failure From 13:02 to 13:09 WO#3402756,NaN,NaN
9,2006-01-03 00:00:00,933,978,995.0,953.0,49.96,3908.96,3755.25,153.71,3942,5.303,72.45,Grid Failure From 8:05 to 9:19 WO#3419549,NaN,NaN
10,2015-01-04 00:00:00,1046,1102,1114.0,1071.0,61.29,4394.29,4210.5,183.79,4430,NaN,NaN,Grid Failure From 16:45 to 18:45 WO#3450753,NaN,NaN
11,2015-01-05 00:00:00,893,939,944.0,902.0,41.55,3719.55,3556.5,163.05,3744,4.8,76.02,The GERMI Plant has Failure The GRID From -1...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
463,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
464,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
465,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
466,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df_test = df_test.reindex(df_test.columns.tolist() + label_list, axis=1)

In [25]:
df_test.head()

,Date,1104500527,1104500529,1.104501e+09,7802195.0,2100570073/ 2100567820/ 2100567898,Total Generation (KWH),Aggregate Meter Reading (KWH),Difference,SEEDs data (KWH),...,MCB Replacement,Inverter Maintenance,Transformer replacement and maintenance,Cable and Fuse maintenance,Plant Shutdown,Inverter,Internet,Battery,Cloudy,Module Cleaning by rains
7,2015-01-01 00:00:00,542,560,509.0,529.0,22.5,2162.5,2035.5,127,2197,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2015-01-02 00:00:00,792,831,842.0,821.0,36.93,3322.93,3177,145.93,3352,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2006-01-03 00:00:00,933,978,995.0,953.0,49.96,3908.96,3755.25,153.71,3942,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2015-01-04 00:00:00,1046,1102,1114.0,1071.0,61.29,4394.29,4210.5,183.79,4430,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2015-01-05 00:00:00,893,939,944.0,902.0,41.55,3719.55,3556.5,163.05,3744,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
def labeling(df_test, label_list):
    final_result = []
    for index, row in df_test.iterrows():
        issue = row["Any Issues/Problems Observed"]
        print(index,issue)
        row_list = []
#         for (i,j) in enumerate(label_dict.iterms()):
#             for value in j:
#                 for label, stop in value:
                    
        for i in label_list:
            if i.lower() in str(issue).lower():
                print("check 1:",i)
                row_list.append(1)
                df_test.loc[index, i] = 1

            else:
                row_list.append(0)
                df_test.loc[index, i] = 0
        #end_for_labels
        final_result.append(row_list)
    #end_for_rows
    #print("\n\n",df_test.iloc[0])
        
    return final_result, df_test

In [36]:
def labeling2(df_test, label_list):
    final_result = []
    for index, row in df_test.iterrows():
        issue = row["Any Issues/Problems Observed"]
        print(index,issue)
        row_list = []
#         for (i,j) in enumerate(label_dict.iterms()):
#             for value in j:
#                 for label, stop in value:
                    
        for i,j in label_dict.items():
            if any(ext in str(issue).lower() for ext in list(map(str.lower, j[0]))):
#                 print(j[1], any(text.lower() in str(issue).lower() for text in j[1]))
                if any(text.lower() in str(issue).lower() for text in j[1]):
                    print("break word appear " + str(j[1]) + " for " + str(j[0]))
                    row_list.append(0)
                    df_test.loc[index, i] = 0
                    continue
                print("check 1:",i)
                row_list.append(1)
                df_test.loc[index, i] = 1

            else:
                row_list.append(0)
                df_test.loc[index, i] = 0
        #end_for_labels
        final_result.append(row_list)
    #end_for_rows
    #print("\n\n",df_test.iloc[0])
        
    return final_result, df_test

In [37]:
res, final_df = labeling2(df_test, label_list)

7 Inverter No- 3 Auto trip 8:50 (modulre fan problem) 9:50 Auto start WO#3381467  & Today I Replaced The D.C.12Amp Fuse Link of The String- 01 --tive in AJB-105 of The Inverter-4 during The Period of 10:25  To  10:30.WO#(3381507)
check 1: Inverter
8 Grid Failure From 13:02 to 13:09 WO#3402756
check 1: Grid Failure
9 Grid Failure From 8:05 to 9:19 WO#3419549
check 1: Grid Failure
10 Grid Failure From 16:45 to 18:45 WO#3450753
check 1: Grid Failure
11  The GERMI Plant has Failure The GRID  From -14:34 to 17:54  (wo#3470232)
  With high Frequency so our  D.O Fuse of  'B' phase blown at 17:54 to 18:40 (WO#3473799)

check 1: Grid Failure
12  Today I Replaced The D.C.12Amp Fuse Link of The String- 08 --tive in AJB-105 of The Inverter-4 during The Period of 10:05  To  10:10.WO#(3486775) & Grid Failure From 15:57 to 18:28 WO#
check 1: Grid Failure
check 1: Inverter
13 Grid Failure From 15:57 to 18:28 WO# 3518160
check 1: Grid Failure
14 Grid Failure From 17:42 to 18:52 WO# 3545933
check 1: Grid Failure
15 Battery water Fileed in 5 kw Battery Bank
check 1: Battery
16 Grid Failure From 13:48 to 13:57 WO# 3593881
check 1: Grid Failure
17 nan
18 Grid Failure From 14:48 to 15:08 WO#3648062 & 15:26 to 15:44 WO#3648693
check 1: Grid Failure
19 nan
20 Cloudy day & Inverer 4 run healthy but exhaust fan faulty
check 1: Cloudy
21 Inverter no-4 run healthy but exhaust fan not working
check 1: Inverter
22 Grid Failure From 11:05 to 11:08 WO#3758192
check 1: Grid Failure
23 Grid Failure From 13:39 to 13:46 WO#3798043
check 1: Grid Failure
24 NO any Issue
25 Transformer -1 & 4 (P.M)
26 NO any Issue
27 fully cloudy Day
check 1: Cloudy
28 NO any Issue
29  Today I Replaced The D.C.12Amp Fuse Link of The String- 04 ++tive in AJB-101 of The Inverter-4 during The Period of 10:25  To  10:30.WO#(3984715)
check 1: Inverter
30 Grid supply failure from 13:29 to 13:34(WO#4024145)
check 1: Grid Failure
31 NO any Issue
32 Grid supply failure from 17:22 to 17:55 (WO#)
check 1: Grid Failure
33 NO any Issue
34 Internet failure
check 1: Internet
35 Grid supply failure from 12:20 to 12:30 (WO#4194605)
check 1: Grid Failure
36 NO any Issue
37 Inverter no- 1,2,3,4, filter cleaning
check 1: Inverter
38 nan
39 NO any Issue
40 NO any Issue
41 Grid supply failure from 9:55 to 12:38 (WO#4378455)
check 1: Grid Failure
42 Module cleaning done Inverter 3 Row N,O,P,Q,R. Total module cleaning 610
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
43 Module cleaning done Inverter 2 & 3 Row K,L,M. Total module cleaning 650
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
44 Module cleaning done Inverter 2 Row I,J. Total module cleaning 650
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
45 Module cleaning done Inverter 2 & 3 Row . Total module cleaning 650 & Grid supply failure from 9:32 to 12:35 (WO#4540622)
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
46 NO any Issue
47 Module cleaning done Inverter 1 & 4 Row A,B.& A,B,C,D,E Total module cleaning 650
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
48 Module cleaning done Inverter 4 Row .& F,G,H,I, Total module cleaning 650
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
49 Module cleaning done Inverter 4 & Trackers, Row .& ,j,k,l, Total module cleaning 640
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
50 Module cleaning done Inverter 3 Row  ,O,P,Q,R,S,T, Total module cleaning 640
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
51 Module cleaning done Inverter 3 & 2 Row  ,K,L,M,N, Total module cleaning 645 &       Replaced The Demaj module as a 11`nd From Uper Last of The  `L` Row,String- 3 JB-110  (OLD Module Sr.no-PB10B068470151) NEW MODULE-PB10B047480118 & 2 Module Replaced Front of the Row no-T string no-1 AJB NO-117 INverter no-3 Damege modulr sr.no-PB10B071470175 NEW Module sr.no-PB10B068470104
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
52 NO any Issue
53 NO any Issue
54 Module cleaning done Inverter 2 Row  ,I,J Total module cleaning 604
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
55 NO any Issue
56 Grid supply failure from 16:14 to 16:19 (WO#5113888) & Module cleaning done Inverter 2 & 1, Row  ,E,F,G,H, Total module cleaning 630
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
57 Module cleaning done Inverter -1 & 4 Row  ,A,B,C,D,Inverter -No-4 Row- A,B,C, Total module cleaning 640
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
58 Module cleaning done Inverter -4 Row -D,E,F,G, Total module cleaning 652
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
59 Grid Failure From - 13:10 to 13:13 (WO#5285421) & Module cleaning done Inverter-4 Row H,I,J, Total module cleaning 630 & Plant shutdown due to replace isolator switch (G.O.D) @ 17:18 to 2:25
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
check 1: Plant Shutdown
60 Our side Grid Failure due to R' Y' B', D.O, fuse Blown & 'B' Phase L.A, Failure @9:21 to 11:35 WO#5340473 & seeds P.M
check 1: Grid Failure
61 Module cleaning done Inverter -4 Row -K,L, & Trackers & Inverter-3 ROW- R,S,T, Total module cleaning 650 & Combiner P.M,
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
62 Module cleaning done Inverter-3 ROW- N,O,P,Q, Total module cleaning 645
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
63 Module cleaning done Inverter-3 &2 ROW- J,K,L,M, Total module cleaning 650
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
64 Module cleaning done Inverter- 2 & 1 ROW- G,H,I, Total module cleaning 660
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
65 Module cleaning done Inverter-  1 ROW- A,B,C,D,E,F, Total module cleaning 670
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
66 Today I Replaced The D.C.12Amp Fuse Link of The String- 03 --tive in AJB-102 of The Inverter-4 during The Period of 15:10  To  15:15.WO#(5732232) & Module cleaning done Inverter-  4 ROW- A,B,C,D,E, Total module cleaning 650
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
67 nan
68 Grid Failure From - 12:02 to 12:07 (WO#5787456) & Fully Cloudy Day
check 1: Grid Failure
check 1: Cloudy
69 Today I Replaced The D.C.12Amp Fuse Link of The String- 07 --tive in AJB-108 of The Inverter-2 during The Period of 10:05  To  10:10.WO#(5847185)
check 1: Inverter
70 Today I Replaced The D.C.12Amp Fuse Link of The String- 03 --tive in AJB-102 of The Inverter-4 during The Period of 15:10  To  15:15.WO#(5914038) & Grid Failure From - 17:20 to 17:32 (WO#5982141)
check 1: Grid Failure
check 1: Inverter
71 Grid supply failure from 15:10 to 15:15 (WO#6007340) & Module cleaning done Inverter 4  Row  ,A,B,C,D,E, Total module cleaning 650
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
72 Module cleaning done Inverter 4  Row  ,F,G,H,I, Total module cleaning 660
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
73 NO any Issue
74 Module cleaning done Inverter 4  Row  ,J,K,L, & Trackers Total module cleaning 660
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
75 Grid supply failure from 16:58 to 17:15 (WO#6308762)
check 1: Grid Failure
76 Module cleaning done Inverter 3  Row O,P,Q,R,S,T, Total module cleaning 660
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
77 Grid supply Failure From - 9:45 to 9:47 & 9:59 to 10:11 & 10:48 to 11:00 & 11:33 to 11:36 & 12:22 to 12:25. Module cleaning done Inverter 2 & 3  Row L,M,N, Total module cleaning 670
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
78 Module cleaning done Inverter 2  Row H,I,J,K, Total module cleaning 665
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
79 Module cleaning done Inverter -1  Row D,E,F,G, Total module cleaning 650
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
80 Module cleaning done Inverter 1 & 4  Row A,B,C,& A,B,C, Total module cleaning 665
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
81 Grid supply failure from 13:40 to 13:47 (WO#6689811) & Module cleaning done Inverter- 4  Row -D,E,F,G, Total module cleaning 660
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
82 Today I Replaced The D.C.12Amp Fuse Link of The String- 02 --tive in AJB-105 of The Inverter-4 during The Period of 16:10  To  16:15.WO#(6754787)
check 1: Inverter
83 Today I Replaced The D.C.12Amp Fuse Link of The String- 04 --tive in AJB-105 of The Inverter-4 during The Period of 10:15  To  10:20.WO#(6812097)
check 1: Inverter
84 NO any Issue
85 Module cleaning done Inverter-3  Row P,Q,R,S,T, Total module cleaning 630
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
86 Module cleaning done Inverter-3 & 2  Row L,M,N,O, Total module cleaning 650
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
87 Today I Replaced The D.C.12Amp Fuse Link of The String- 04 ++tive in AJB-101 of The Inverter-4 during The Period of 12:20  To  12:25.WO#(7104864) & Grid supply failure from 8:07 to 8:13 (WO#7098699) & Module cleaning done Inverter- 4  Row -H,I,J,K, Total module cleaning- 650
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
88 Grid failure from - early morning to 9:26. Module cleaning done Inverter-1  Row D,E,F,G,Total module cleaning 650
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
89 NO any Issue
90 Module cleaning done Inverter-1 & 4  Row A,B,C,& A,B,C, Total module cleaning 640 & Inverter No-4 AJB No- 104 MCB Trip 12:40 to 14:02 WO#7318204
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
91 Module cleaning done Inverter-4  Row D,E,F,G, Total module cleaning 660
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
92 Module cleaning done Inverter-4  Row H,I,J,K,L, & Tracker Total module cleaning 720
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
93 Today I Replaced The D.C.12Amp Fuse Link of The String- 02 --tive in AJB-116 of The Inverter-3 during The Period of 10:35  To  10:40.WO#(7506678) & Module cleaning done Inverter- 3 ROW- ,P,Q,R,S,T, Total module cleaning 630
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
94 Module cleaning done Inverter-3 & 2  Row L,M,N,O, &  Total module cleaning 660
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
95 Module cleaning done Inverter-1 & 2  Row ,H,I,J,K, &  Total module cleaning 670
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
96 Grid supply failure from 16:51 to 18:02 (WO#7717067)
check 1: Grid Failure
97 Module cleaning done Inverter-1  Row ,A,B,C,D,E,F,G, &  Total module cleaning 685
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
98 Module cleaning done Inverter-4  Row ,A,B,C,D,E, &  Total module cleaning 630 & Today I Replaced The D.C.12Amp Fuse Link of The String- 01 --tive in AJB-106 of The Inverter-2 during The Period of 10:35  To  10:40.WO#(7849439) & Replace the silica gel
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
99 nan
100 Module cleaning done Inverter-4  Row ,F,G,H,I, &  Total module cleaning 650
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
101 Module cleaning done Inverter-4  Row ,J,K,L, & Trackers  Total module cleaning 610
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
102 Module cleaning done Inverter-3 Row P,Q,R,S,T & Total module cleaning 630
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
103 Module cleaning done Inverter-2 & 3 Row L,M,N,O & Total module cleaning 660. & Grid supply failure from 18:12 to 18:30 (WO#8175587) & couldy day
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
104 Grid supply failure from - 9:06 to 9:12 & couldy day
check 1: Grid Failure
105 Module cleaning done Inverter-2  Row ,H,I,J,K,& Total module cleaning 670. & Grid supply failure from 10:02 to 10:22 (WO#8286657)
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
106 Module cleaning done Inverter-2 &1 Row E,F,G, & Total module cleaning 620
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
107 Module cleaning done Inverter-1 Row ,A,B,C,D & Total module cleaning 590
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
108 NO any Issue
109 Module cleaning done Inverter-4 Row ,A,B,C,D, & Total module cleaning 580
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
110 Module cleaning done Inverter-4 Row ,E,F,G,H, & Total module cleaning 650 & Rain
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
111 Grid supply failure From 9:45 to 9:49 & 16:03 to 16:09 (WO#8750195) (WO#8816841)
check 1: Grid Failure
112 NO any Issue
113 NO any Issue
114 L.T PANEL P.M
115 Module cleaning done Inverter-4  Row ,A,B,C,D,E,& Total module cleaning 630. & Grid supply failure from 13:17 to 13:24 (WO#9086294)
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
116 Module cleaning done Inverter-4  Row ,F,G,H,I, &  Total module cleaning 650
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
117 Module cleaning done Inverter-4  Row ,J,K,L, &  Total module cleaning 660
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
118 NO any Issue
119 Today I Replaced The 2 D.C.12Amp Fuse Link of The String- 09++tive in AJB-104 of The Inverter-1 & 09--tive AJB-105  during The Period of 10:15  To  10:25.WO#(9402652) & Module cleaning done Inverter-3  Row ,P,Q,R,S,T, &  Total module cleaning 620
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
120 Module cleaning done Inverter-3 &2  Row ,L,M,N,O, &  Total module cleaning 690
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
121 Module cleaning done Inverter-2  Row ,H,I,J,K, &  Total module cleaning 710
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
122 Module cleaning done Inverter-2 & 1  Row ,D,E,F,G, &  Total module cleaning 680
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
123 Module cleaning done Inverter-1 & 4  Row ,A,B,C, & ,A,B,C, &  Total module cleaning 650
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
124 Module cleaning done Inverter-4  Row-,D,E,F,G, &  Total module cleaning 650
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
125 NO any Issue
126 Module cleaning done Inverter-4  Row-,H,I,J,K, &  Total module cleaning 660
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
127 Module cleaning done Inverter-4 & 3 Row-,L, -R,S,T,& Tracker &  Total module cleaning 620  & Control Building P.M & Inverter P.M (1&2)
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
128 Module cleaning done Inverter-3 Row- N,O,P,Q, &  Total module cleaning 630  & C.R Panel P.M & Inverter P.M (3&4) & Internet Failure (POE POWER ADAPTER FAILURE)14:45
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
check 1: Internet
129 Module cleaning done Inverter-3 & 2  Row- J,K,L,M  &  Total module cleaning 680
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
130 nan
131 Grid supply failure from 14:59 to 15:15
check 1: Grid Failure
132 NO any Issue
133 NO any Issue
134 Module cleaning done Inverter-1 & 2  Row- G,H,I, &  Total module cleaning 650
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
135 Module cleaning done Inverter-1 Row- ,C,D,E,F, &  Total module cleaning 660
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
136 Module cleaning done Inverter-1 & 4 Row- ,A,B &,A,B,C,D, & Total module cleaning 670
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
137 Module cleaning done Inverter-4 Row- ,E,F,G,H, & Total module cleaning 690
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
138 Module cleaning done Inverter-4 Row- ,I,J,K,L, & Total module cleaning 670
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
139 Module cleaning done Inverter-3 & Trackers Row- ,Q,R,S,T, & Total module cleaning 630
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning

140 NO any Issue
141 Module cleaning done Inverter-3 & Row- ,M,N,O,P, & Total module cleaning 650
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
142 Inverter#3 did not wake up due to auto reset indication so reset it at 9:35am and started the inverter. & Module cleaning done Inverter-3 & 2 Row- ,J,K,L, & Total module cleaning 680
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
143 5 KV UPS System D.C, Volt Low so Bypass the system plant Trip 15:15 to 16:10 WO# & Module cleaning done Inverter-2 & Row- ,G,H,I, & Total module cleaning 650 & Cloud and Rain
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
144 Night time 11KV Grid Failure so our plant VCB Trip plant started 9:05 & Two Time Grid Failure From-10:58 to 11:21 & 14:25 to 14:35 & Module cleaning done Inverter-1  Row- ,D,E,F, & Total module cleaning 640 & Cloud and Rain
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
145 Grid Failure From -11:09 to 11:16 WO# & Module cleaning done Inverter-1  Row- ,A,B,C, & Total module cleaning 350
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
146 Today I Replaced The D.C.12Amp Fuse Link of The String- 04 ++tive in AJB-104 of The Inverter-4 during The Period of 19:35  To  9:40.WO#() & Module cleaning done Inverter- 4 ROW- ,A,B,C,D,E, Total module cleaning 600
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
147 Array P.M
148 Module cleaning done Inverter-4  Row- ,F,G,H, & Total module cleaning 600
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
149 Module cleaning done Inverter-4  Row- ,I,J,K,L, & Total module cleaning 670 & Grid Failure From -16:15 to 16:23 WO# & Combiner P.M (AJB-100 to 117 -Crystallin side 750 KW )
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
150 Module cleaning done Inverter-3 & Trackers Row- ,P,Q,R,S,T, & Total module cleaning 650 & Combiner P.M (AJB-100 to 105 -Thinfilm side 250 KW )
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
151 Module cleaning done Inverter-3 & 2 Row- ,L,M,N,O, & Total module cleaning 680 & Seeds P.M
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
152 Module cleaning done Inverter- 2 Row- ,I,J,K, & Total module cleaning 710
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
153 Module cleaning done Inverter-2 & 1 Row- ,F,G,H, & Total module cleaning 650 & Grid Failure From -08:07 to 08:15 WO#12532233
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
154 NO any Issue
155 Module cleaning done Inverter- 1 Row- C,D,E, & Total module cleaning 600 & Grid Failure From -07:20 to 08:05 WO#12736715
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
156 Module cleaning done Inverter- 1 & 4 Row- ,A,B, & A,B,C,D, & Total module cleaning- 610
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
157 Module cleaning done Inverter- 4 Row- ,E,F,G, & Total module cleaning- 560
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
158 Module cleaning done Inverter- 4 Row- ,H,I,J, & Total module cleaning- 596
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
159 Module cleaning done Inverter- 4 & 3 & Trackers Row- ,K,L,& R,S,T, & Total module cleaning 660 & Grid Failure From -12:52 to 12:57 WO#13149762 & Tracker P.M
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
160 Module cleaning done Inverter- 3 Row- ,N,O,P,Q, & Total module cleaning- 660
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
161 Grid failure from night time so our plant side V.C.B. trip Morning 8:00a.m on V.C.B. plant started 8:00a.m.WO#13316368
check 1: Grid Failure
162 nan
163 Module cleaning done Inverter- 2 Row- ,H,I,J, & Total module cleaning- 670
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
164 Module cleaning done Inverter- 2 Row- ,H,I,J, & Total module cleaning- 670
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
165 Module cleaning done Inverter- 1 Row- E,F,G, & Total module cleaning 580 & Grid Failure From -12:55 to 13:05 WO# & Trackers 4 S.Q. m.m. 4 core cable  B Phase Ground folt (Tracker Inverter no-3 S.M.A. power supply failure)
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
166 Module cleaning done Inverter- 1 Row- A,B,C,D, 550 & Total module cleaning 550 & Grid Failure From -08:20 to 08:45 WO#13640469
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
167 Module cleaning done Inverter- 4 Row- ,A,B,C,D,E, & Total module cleaning- 630
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
168 Module cleaning done Inverter- 4 Row- ,F,G,H, & Total module cleaning- 594
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
169 Grid Failure From -17:48 to 17:55 WO# & Inverter no-1 ABB, From- 17:55 inverter  not started (sleep mode)
check 1: Grid Failure
check 1: Inverter
170 Module cleaning done Inverter- 4 Row- ,I,J,K,L, & Total module cleaning- 650
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
171 Module cleaning done Inverter- 3 Row- ,P,Q,R,S,T, & Total module cleaning- 630
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
172 Today Eight time Grid failure-8:00 to 8:50 , 12:32 to 12:42, 14:50 to 14:55, 15:20 to 15:26 , 15:50 to 15:55, 16:46 to 16:50, 17:15 to 17:19, 17:31 to 17:59 & Inverter no-1,2,3, Emergency stop reset Inverter started 9:10 & Inverter no-1 Grid folt Err code NONFOLT(8189 A.C. VOLT LOW) 15:20 TO 16:20
check 1: Grid Failure
check 1: Inverter
173 Module cleaning done Inverter- 3 Row- ,L,M,N,O, 670 & Total module cleaning 670 & Grid Failure From -12:58 to 13:06 WO#
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
174 NO any Issue
175 NO any Issue
176 NO any Issue
177 Module cleaning done Inverter- 3 Row- ,P,Q,R,S,T, & Total module cleaning 650 & Grid Failure From -12:01 to 12:07 WO#
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
178 Module cleaning done Inverter- 3 Row- ,L,M,N,O, & Total module cleaning- 670
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
179 Module cleaning done Inverter- 1 & 2 Row- ,G,H,I,J,K, & Total module cleaning 900 & Grid Failure From -07:40 to 08:00 & 10:24 to 10:39 WO#
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
180 Module cleaning done Inverter- 1 Row- ,A,B,C,D,E, & Total module cleaning 950 & Grid Failure From -12:10 to 12:15 WO#14683274
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
181 Module cleaning done Inverter- 4 Row- ,A,B,C,D,E, & Total module cleaning- 630
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
182 Module cleaning done Inverter- 4 Row- ,F,G,H, & Total module cleaning- 594
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
183 NO any Issue
184 Module cleaning done Inverter- 4 Row- ,I,J,K,L, & Trackers & Total module cleaning 750 & Grid Failure From -08:13 to 08:22 WO#14882219 & cloudy day
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
check 1: Cloudy
185 Module cleaning done Inverter- 3 Row- ,P,Q,R,S,T, & Total module cleaning- 650 & cloudy day
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
check 1: Cloudy
186 Grid Failure From- 15:08 to 16:05 Inverters note started sleep mode because D.C.Valltege low heavy rain & Grid Failure From- 17:13 to 17:39
check 1: Grid Failure
check 1: Inverter
187 Grid Failure From- 14:22 to 14:30 WO#15038762
check 1: Grid Failure
188 Grid Failure From- 07:54 to 8:02 WO#1508660
check 1: Grid Failure
189 Grid Failure From- 15:00 to 15:20 WO#15158620
check 1: Grid Failure
190 NO any Issue
191 Module cleaning done Inverter- 4 Row- ,A,B,C,D,E, & Total module cleaning- 630
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
192 Module cleaning done Inverter- 4 Row- ,F,G,H, & Total module cleaning 594 & Grid Failure From -13:13 to 13:20 WO#15323914
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
193 nan
194 Module cleaning done Inverter- 4 Row- ,I,J,K,L, & Total module cleaning- 690
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
195 Module cleaning done Inverter- 3 & Trackers Row- ,P,Q,R,S,T, & Total module cleaning- 710
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
196 Module cleaning done Inverter- 3 Row- ,L,M,N,O, & Total module cleaning 670 & Grid Failure From -11:36 to 11:42 WO#15472920
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
197 Module cleaning done Inverter- 2 Row- ,I,J,K, & Total module cleaning 710 & Grid Failure From -18:50 to 18:02 WO#15545727
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
198 NO any Issue
199 Module cleaning done inverter -1 Row- G,H & Total module cleaning 504 & Cloudy day
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
check 1: Cloudy
200 Module cleaning done Inverter- 1 Row- ,D,E,F, & Total module cleaning 462 & Grid Failure From -11:36 to 11:46 & 15:01 to 15:40 WO#
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
201 Module cleaning done inverter -1 Row- A,B,C, & Total module cleaning 540
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
202 Module cleaning done inverter -4 Row- A,B,C,D,E, & Total module cleaning 630
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
203 Module cleaning done inverter -4 Row- ,F,G,H, & Total module cleaning 594
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning

204 Module cleaning done Inverter- 4 Row- ,I,J,K,L, & Total module cleaning- 690 & Grid Failure From -18:03 to 18:09 WO#
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
205 NO any Issue
206 NO any Issue
207 Module cleaning done Inverter- 3 & Trackers Row- ,Q,R,S,T, & Total module cleaning- 354 & Grid Failure From -16:57 to 17:03 WO#
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
208 Module cleaning done Inverter- 3  Row- ,N,O,P,, & Total module cleaning- 546 & Grid Failure From -17:58 to 18:04 WO#
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
209 Module cleaning done inverter -2 & 3 Row- ,L,M, & Total module cleaning 504
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
210 Module cleaning done inverter -2 Row- ,J,K, & Total module cleaning 570
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
211 Inverter-2  AJB -106 String -7 MC4 connector bourned so replace connector and string started WO#() & Module cleaning done inverter -2 & 1 Row- ,I,J, & Total module cleaning 504
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
212 nan
213 Internet failure & Module cleaning done inverter -1 Row- ,E,F,G, & Total module cleaning 489
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
check 1: Internet
214 Grid Failure From-11:40 to 14:08 WO#
check 1: Grid Failure
215 nan
216 11K.V side (G.O.D. Swich) R, phase sparking so maintains R, phase sutdown plant-10:03 to 10:20 WO#
217 Grid Failure From-15:45 to 16:33 WO#
check 1: Grid Failure
218 nan
219 nan
220 nan
221 Grid Failure From-28-7-2015-08:58 to 30-7-2015 -14:43 WO#16824672
check 1: Grid Failure
222 Grid Failure From-28-7-2015-08:58 to 30-7-2015 -14:43 WO#16824672
check 1: Grid Failure
223 Grid Failure From-28-7-2015-08:58 to 30-7-2015 -14:43 WO#16824672
check 1: Grid Failure
224 Grid Failure From-08:42 to 10:30 WO#
check 1: Grid Failure
225 nan
226 nan
227 nan
228 Inverter no-3 morning time note wakeup Err-no-ISU (8185) Folt reset manualy inverter started -10:01 WO# & Grid Failure From-15:40 to 15:49 WO#17070345
check 1: Grid Failure
check 1: Inverter
229 Module cleaning done inverter -4 Row- ,A,B,C,D,E, & Total module cleaning -630
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
230 Module cleaning done Inverter- 4  Row- ,F,G,H, & Total module cleaning- 594 & Grid Failure From -06:30 to 06:40 WO#17177576
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
231 Module cleaning done inverter -4 Row- ,I,J,K,L,, & Total module cleaning -690
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
232 Module cleaning done inverter -3 & Trackers Row- ,O,P,Q,R,S,T, & Total module cleaning -604
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
233 Module cleaning done Inverter- 3&2  Row- ,L,M,N, & Total module cleaning- 714 & Grid Failure From -15:03 to 15:10 WO#17364939
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
234 Inverter no-2 ABB-Auto Trip becose Inverters Bloware fan (supply card) Bourned Inverter trip -12:20 to 15:55 WO#
check 1: Inverter
235 Inverter no-2 ABB-Auto Trip becose Inverters Bloware fan (supply card) Bourned Inverter trip -13:20 to 17:05 WO# & Module cleaning done inverter -2  Row- ,J,K, & Total module cleaning -567
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
236 Inverter no-2 ABB-Auto Trip becose Inverters Bloware fan (supply card) Bourned Inverter trip -10:00 to 16:00 WO# & Module cleaning done inverter -2&1  Row- ,H,I, & Total module cleaning -504
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
237 Inverter no-2 ABB-Auto Trip becose Inverters Bloware fan (supply card) Bourned Inverter trip -10:20 to 10:40 WO#
check 1: Inverter
238 nan
239 Two time Grid Failure From-9:50 to 9:59 WO#17658237 & 14:20 to 14:40 WO#17660923
check 1: Grid Failure
240 nan
241 nan
242 nan
243 Inverter no-3 morning time note wakeup Err-no-ISU (8185) Folt reset manualy inverter started -09:40 WO#
check 1: Inverter
244 Inverter no-4 morning time not wakeup Err code-0252 (IGBT SWICH) WO#
check 1: Inverter
245 Inverter no-2 ABB sutdown to inverter 11:20 to 12:25 replace the Than card inverter started 12:25 WO#() & Inverter no-1,2,3,SMA Trackers sutdown to inverters 10:40 to 14:10 Mager testing Folt Faund inverter no-3 Folt issue sold out WO#() & Combiner P.M (750 Kw side)
check 1: Inverter
246 Combiner P.M (250K.w) & Seeds P.M
247 nan
248 nan
249 Inverter no-1,2,3,4, inverters Filter cleaning
check 1: Inverter
250 Inverter no-4 inverter started 10:15 a.m WO#()
check 1: Inverter
251 Module cleaning done inverter -4 Row- ,A,B,C,D,E, & Total module cleaning -630
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
252 Module cleaning done inverter -4 Row- ,F,G,H, & Total module cleaning -594
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
253 Module cleaning done inverter -4 Row- ,I,J,K,L, & Total module cleaning -690 & Grid Failure From-10:00 to 10:05 WO#()
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
254 nan
255 Two time Grid Failure From-07:09 to 07:21 & 11:28 to 11:38 WO#()
check 1: Grid Failure
256 Module cleaning done inverter -3 & Trackers Row- ,O,P,Q,R,S,T, & Total module cleaning -604 & Grid Failure From-13:57 to 14:07 WO#(18593384)
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
257 nan
258 Module cleaning done inverter -3 & 2 Row- ,L,M,N, & Total module cleaning -714 & Two Time Grid Failure From-06:18 to 06:25 & 10:15 to 10:20 WO#(18632721 & 18635335)
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
259 Module cleaning done inverter -2  Row- ,I,J,K, & Total module cleaning -840  & Grid Failure From-10:50 to 10:59 WO#(18695171)
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
260 Module cleaning done inverter -1 Row- ,F,G,H, & Total module cleaning -630
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
261 Module cleaning done inverter -1  Row- ,A,B,C,D,E, & Total module cleaning -483  & Grid Failure From-16:07 to 16:58 WO#(18814517)
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
262 nan
263 nan
264 Inverter no-4 shutdown 13:00 to 13:28 for maintance Replace IGBT 'Y' Phase inverter started 13:28 WO#() & Module cleaning done inverter -4 Row- ,A,B,C,D,E, & Total module cleaning -630
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
265 Module cleaning done inverter -4 Row- ,F,G,H, & Total module cleaning -594
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
266 Today I Replaced The 2 D.C.12Amp Fuse Link of The String- 07++tive in AJB-116 of The Inverter-3 & 03--tive Line AJB-100 Inverter no-4  during The Period of 10:30  To  10:45.WO#(19058966) & Module cleaning done Inverter-4  Row ,I,J,K,L, &  Total module cleaning 690
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
267 Two time Grid Failure From-14:36 to 14:47 & 16:25 to 17:55 WO#()
check 1: Grid Failure
268 Module cleaning done inverter -3 & Trackers  Row- ,O,P,Q,R,S,T, & Total module cleaning -604  & Grid Failure From-18:35 to 19:05 WO#()
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
269 Module cleaning done inverter -3 & 2  Row- ,L,M,N, & Total module cleaning -714  & Grid Failure From-17:05 to 18:30 WO#(19203752)
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
270 Three Time Grid Failure From-07:02 to 07:10 & 09:07 to 9:34 & 11:28 to 11:33 WO#() & Today I Replaced The 2 D.C.12Amp Fuse Link of The String- 03++tive in AJB-101 of The Inverter-4 & 03--tive Line AJB-102 Inverter no-4  during The Period of 10:45 To 11:00.WO#(19237302)
check 1: Grid Failure
check 1: Inverter
271 Module cleaning done inverter -2 Row- ,I,J,K, & Total module cleaning -840
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
272 Module cleaning done inverter -1 Row- ,F,G,H, & Total module cleaning -630
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning

273 Module cleaning done inverter -1 Row- ,A,B,C,D, E, & Total module cleaning -483
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
274 Module cleaning done inverter -4 Row- ,A,B,C,D, E, & Total module cleaning -630
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
275 Grid Failure From-14:40 to 14:54 WO#19495606 & Module clean by Rain
check 1: Grid Failure
276 Grid Failure From-yesterday night  to 18:05 WO# & Module clean by Rain & Main Transformer P.M
check 1: Grid Failure
277 Grid Failure From-08:00 to 16:20 WO#(A.C.Voltage low) & Module clean by Rain
check 1: Grid Failure
278 Inverter no-4 morning time not wake up Err no-0012 A.C.Voltage low reset Err code inverter started 11:25WO#19640583 & Inverter no-1 ABB 250 KVA Bloware than card failure Auto trip 13:00 to 13:35 WO#19640666 & Module clean by Rain
check 1: Inverter
279 Inverter no-1 ABB 250 KVA morning time note wake up Blowre than card Failure By pass 3 phase supply blowre & inverter started 10:08 WO#19676055 Module clean by Rain
check 1: Inverter
280 Grid Failure From-10:02 to 10:54 WO#(19734203) & Module clean by Rain
check 1: Grid Failure
281 Today I Replaced The D.C.12Amp Fuse Link of The String- 05++tive in AJB-101 of The Inverter-1  during The Period of 10:30 To 10:45.WO#(19839635)
check 1: Inverter
282 Grid Failure (low voltege) From-08:15 to 12:27 WO#19835946
check 1: Grid Failure
283 Module cleaning done inverter -4  Row- ,A,B,C,D,E, & Total module cleaning -630  & Grid Failure From-12:41 to 12:50 WO#(19898067)
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
284 Grid Failure From-16:28 to 17:58 WO#(19957162)
check 1: Grid Failure
285 Module cleaning done inverter -4  Row- ,F,G,H, & Total module cleaning -594  & Grid Failure From-09:22 to 09:32 WO#(19991956)
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
286 Module cleaning done inverter -4  Row- ,I,J,K,L, & Total module cleaning -690
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
287 Grid Failure From-08:30 to 10:05 WO#(20099787) & Inverter No-4 sleep mode 10:07 to 17:05 Err code - sleep mode inverter WO#20108412
check 1: Grid Failure
check 1: Inverter
288 nan
289 Module cleaning done inverter -3 & Trackers  Row- ,O,P,Q,R,S,T, & Total module cleaning -604
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
290 nan
291 Module cleaning done inverter -3 & 2  Row- ,L,M,N, & Total module cleaning -714
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
292 Grid Failure From-09:06 to 09:13 WO#(20317939)
check 1: Grid Failure
293 Module cleaning done inverter -2  Row- ,I,J,K, & Total module cleaning -840  & Grid Failure From-07:48 to 07:55 WO#(20355081)
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
294 Module cleaning done inverter -1  Row- ,F,G,H, & Total module cleaning -630
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
295 Module cleaning done inverter -1 & 4  Row- ,A,B,C,D,E, & A,B,C,D,E, & Total module cleaning -1103
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
296 Module cleaning done inverter -1 & 4  Row- ,A,B,C,D,E, & A,B,C,D,E,F,G,H, & Total module cleaning -2188
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
297 Module cleaning done inverter -2 & 3  Row- ,K,L,M, & Total module cleaning -770  & Grid Failure From-13:42 to 13:55 & 16:43 to 16:54 WO#(20521472)
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
298 Module cleaning done inverter -2  Row- ,H,I,J, & Total module cleaning -798  & Grid Failure From-09:45 to 09:55 & 16:31 to 16:42 & 17:19 to 17:25 WO#()
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
299 Grid Failure From-06:15 to 12:37 WO#()
check 1: Grid Failure
300 6 Time Grid Failure From-08:45 to 08:56 & 9:00 to 9:22 & 10:11 to 10:28 & 15:52 to 15:58 & 17:05 to 17:52 & 17:37 to 17:43 WO#()
check 1: Grid Failure
301 Night time grid failure to 8:32 WO#20699781 & 17:51 to 17:56
check 1: Grid Failure
302 Module cleaning done inverter -4  Row- ,A,B,C,D,E, & Total module cleaning -630  & Grid Failure From-16:28 to 16:33 WO#(20757004)
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
303 Module cleaning done inverter -4  Row- ,F,G,H, & Total module cleaning -594 & L.T PANEL P.M
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
304 Module cleaning done inverter -4  Row- ,I,J,K,L, & Total module cleaning -690
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
305 Module cleaning done inverter -3 & Trackers Row- ,O,P,Q,R,S,T, & Total module cleaning -604  & Grid Failure From-16:28 to 16:33 WO#(20757004)
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
306 nan
307 Module cleaning done inverter -3 & 2  Row- ,L,M,N, & Total module cleaning -714
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
308 Module cleaning done inverter -2  Row- ,I,J,K, & Total module cleaning -840
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
309 Today I Replaced The 3 D.C.12Amp Fuse Link of The String- 04--tive in AJB-101 of The Inverter-4 & String no-2 & 4 --tive line AJB -105 Inverter no-4 during The Period of 09:40 To 09:50.WO#(21052510) & Module cleaning done inverter -1  Row- ,F,G,H, & Total module cleaning -630
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
310 Module cleaning done inverter -1  Row- ,A,B,C,D,E, & Total module cleaning -483
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
311 Module cleaning done inverter -4  Row- ,A,B,C,D,E, & Total module cleaning -630
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
312 Grid Failure From-17:21 to 17:32 WO#21218179
check 1: Grid Failure
313 Grid Failure From-11:10 to 11:22 WO#21252902
check 1: Grid Failure
314 Module cleaning done inverter -4  Row- ,F,G,H, & Total module cleaning -594
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
315 Module cleaning done inverter -4  Row- ,I,J,K,L, & Total module cleaning -690
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
316 Module cleaning done inverter -3 & Trackers Row- ,O,P,Q,R,S,T, & Total module cleaning -604  & Grid Failure From-08:57 to 09:15 WO#(21392605) & Today Replace Transformers New Bridhar & slicagel (2,3,4,)
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
317 Module cleaning done inverter -3 & 2 Row- ,L,M,N, & Total module cleaning -714  & Grid Failure From-16:49 to 16:55 WO#() Transformers p.m & Inverter P.M (1,2,)
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
318 Module cleaning done inverter -2  Row- ,I,J,K, & Total module cleaning -840 & Inverter P.M (3,4)
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
319 Module cleaning done inverter -1  Row- ,F,G,H, & Total module cleaning -630
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
320 nan
321 nan
322 Module cleaning done inverter -1 & 4 Row- ,A,B,C,D,E, & A,B, & Total module cleaning -645  & Grid Failure From-08:49 to 08:54 WO#(21624101)
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
323 Module cleaning done inverter - 4 Row- ,C,D,E,F, & Total module cleaning -630  & Grid Failure From-08:32 to 08:53 WO#(21667547)
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
324 Module cleaning done inverter - 4 Row- ,G,H,I, & Total module cleaning -594  & Grid Failure From-14:50 to 16:37 WO#(21738513)
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
325 Module cleaning done inverter -4,3,& Trackers Row- ,J,K,L,& S,T, & Total module cleaning -612
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
326 Module cleaning done inverter -3 Row- ,N,O,P,Q,R, & Total module cleaning -756  & Grid Failure From-09:45 to 10:14 & 13:53 to 14:35 WO#(21826715)
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
327 Module cleaning done inverter - 3 & 2 Row- ,K,L,M, & Total module cleaning -777  & Grid Failure From-15:57 to 16:05 WO#(21892950)
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
328 nan
329 Module cleaning done inverter -1 & 2 Row- ,H,I,J, & Total module cleaning -798
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning

330 Module cleaning done inverter -1 Row- ,E,F,G, & Total module cleaning -546
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
331 nan
332 nan
333 nan
334 Module cleaning done inverter -1 & 4 Row- ,A,B,C,D, & A,B, & Total module cleaning -498
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
335 nan
336 Module cleaning done inverter -4 Row- ,C,D,E,F, & Total module cleaning -630  & Grid Failure From-07:49 to 08:07 & 14:01 to 14:59 & 17:10 to 17:27 WO#()
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
337 Module cleaning done inverter -4 Row- ,G,H,I, & Total module cleaning -594  & Grid Failure From-16:13 to 16:20 & 17:00 to 17:28 WO#()
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
338 Module cleaning done inverter -4 & 3 Row- ,J,K,L, & S,T, & Trackers & Total module cleaning -612  & Grid Failure From-09:49 to 10:04 WO#()
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
339 Module cleaning done inverter -3 Row- ,N,O,P,Q,R, & Total module cleaning -756
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
340 Module cleaning done inverter -3 & 2 Row- ,K,L,M, & Total module cleaning -777
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
341 Module cleaning done inverter -1 & 2 Row- ,H,I,J, & Total module cleaning -798 & seeds P.M
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
342 nan
343 Module cleaning done inverter -1 Row- ,E,F,G, & Total module cleaning -546
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
344 Module cleaning done inverter -4 & 1 Row- ,A,B,C,D,& A,B, & Total module cleaning -498  & Grid Failure From-15:09 to 15:17 WO#()
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
345 Module cleaning done inverter -4 Row- ,C,D,E,F, & Total module cleaning -630
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
346 Module cleaning done inverter -4 Row- ,G,H,I & Total module cleaning -594
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
347 Module cleaning done inverter -4 & 3 Trackers Row- ,J,K,L, & ,S,T, & Total module cleaning -612  & Grid Failure From-17:08 to 17:19 WO#(22855523)
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
348 Module cleaning done inverter -3 Row- ,N,O,P,Q,R, & Total module cleaning -756  & Grid Failure From-11:13 to 11:45 WO#(22889812)
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
349 Today I Replaced The D.C.12Amp Fuse Link of The String- 07--tive in AJB-105 of The Inverter-1 during The Period of 11:10 To 11:15.WO#(22939578) & Trackers P.M
check 1: Inverter
350 Module cleaning done inverter -2 & 3 Row- ,K,L,M, & Total module cleaning -777 & Transformer No-2 300kva P.M
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
351 nan
352 today ABB engineer has come at site for replacing blower than card so for replacing purpose we took shut down at 15:50 and switching on at 16:45.
But that card couldn’t work so they will get to fix some other card by this week. & Module cleaning done inverter -1 & 2 Row- ,H,I,J, & Total module cleaning -798
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
353 Today I Replaced The D.C.12Amp Fuse Link of The String- 05--tive in AJB-105 of The Inverter-1 during The Period of 10:15 To 10:20.WO#() & Module cleaning done inverter -1 Row- ,E,F,G, & Total module cleaning -546  & Grid Failure From-16:59 to 17:22 WO#()
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
354 Module cleaning done inverter -4 & 1 Row- ,A,B,C,D,& A,B, & Total module cleaning -498
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
355 Module cleaning done inverter -4 Row- C,D,E,F & Total module cleaning -630 & Grid failure from - 12:40 to 12:49 WO#
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
356 nan
357 Module cleaning done inverter -4 Row- G,H,I, & Total module cleaning -594
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
358 Module cleaning done inverter -4 & Trackers Row- ,J,K,L,& S,T, & Total module cleaning -612
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
359 Module cleaning done inverter -3 Row- ,N,O,P,Q,R, & Total module cleaning -756
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
360 Module cleaning done inverter -3 & 2 Row- ,K,L,M, & Total module cleaning -777
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
361 Module cleaning done inverter -1 & 2 Row- ,H,I,J, & Total module cleaning -798
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
362 Module cleaning done inverter -1 Row- ,E,F,G, & Total module cleaning -546 & Grid failure from - 10:32 to 10:38 WO#()
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
363 Module cleaning done inverter -1 & 4 Row- ,A,B,C,D & A,B & Total module cleaning -498
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
364 Module cleaning done inverter -4 Row- C,D,E,F, & Total module cleaning -630 & Grid failure from - 14:04 to 14:09 WO#()
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
365 Module cleaning done inverter -4  Row- ,G,H,I, & Total module cleaning -594
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
366 Today I Replaced The D.C.12Amp Fuse Link of The String- 05--tive in AJB-115 of The Inverter-1 during The Period of 10:20 To 10:25.WO#() & Module cleaning done inverter -3&4 Trackers Row- ,J,K,L, & S,T, & Total module cleaning -612
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
367 Module cleaning done inverter -3  Row- ,N,O,P,Q,R, & Total module cleaning -756
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
368 Module cleaning done inverter -2 & 3 Row- ,K,L,M, & Total module cleaning -777 & Grid failure from - 17:09 to 17:13 WO#()
check 1: Grid Failure
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
369 Module cleaning done inverter -1 & 2  Row- ,H,I,J, & Total module cleaning -798
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
370 Module cleaning done inverter -1  Row- ,E,F,G, & Total module cleaning -546
break word appear ['Module Cleaning'] for ['Inverter']
check 1: Module Cleaning
371 nan
372 nan
373 Inverter No-1,2,3,4, Filter Cleaning & Inverter No- 4 (P.M)
check 1: Inverter
374 nan
375 nan
376 nan
377 nan
378 nan
379 Grid Failure From-08:20 to 14:40 WO#24330844
check 1: Grid Failure
380 Inverter no- 1 ABB (250KW) Auto trip 10:00 to 17:00 wo#
check 1: Inverter
381 Inverter-no-1 ABB was shut down from 12:30 to 14:00 for replacing the IGBT blower by ABB engineer but job could't completed
check 1: Inverter
382 Inverter-no-1 ABB was shut down from 13:25 to 16:00 & Inverter-no-2 was shut down from14:00 to 15:30 for replacing the IGBT blower by ABB engineer but job could't completed
check 1: Inverter
383 nan
384 nan
385 nan
386 nan
387 nan
388 nan
389 nan
390 nan
391 nan
392 nan
393 nan
394 nan
395 nan
396 nan
397 nan
398 nan
399 nan
400 nan
401 nan
402 nan
403 nan
404 nan
405 nan
406 nan
407 nan
408 nan
409 nan
410 nan
411 nan
412 nan
413 nan
414 nan
415 nan
416 nan
417 nan
418 nan
419 nan
420 nan
421 nan
422 nan
423 nan
424 nan
425 nan
426 nan
427 nan
428 nan
429 nan
430 nan
431 nan
432 nan
433 nan
434 nan
435 nan
436 nan
437 nan
438 nan
439 nan
440 nan
441 nan
442 nan
443 nan
444 nan
445 nan
446 nan
447 nan
448 nan
449 nan
450 nan
451 nan
452 nan
453 nan
454 nan
455 nan
456 nan
457 nan
458 nan
459 nan
460 nan
461 nan
462 nan
463 nan
464 nan
465 nan
466 nan

In [29]:
# res, final_df = labeling(df_test, label_list)

In [30]:
#res

In [38]:
pd.set_option("display.max_columns", None)

In [39]:
pd.set_option("display.max_rows", None)

In [40]:
final_df

,Date,1104500527,1104500529,1.104501e+09,7802195.0,2100570073/ 2100567820/ 2100567898,Total Generation (KWH),Aggregate Meter Reading (KWH),Difference,SEEDs data (KWH),Insolation,PR (%),Any Issues/Problems Observed,WO#,NO-OFF-CLEAN MODULES,Grid,Module Cleaning,Rainy day,No Module Cleaning,MCB Replacement,Inverter Maintenance,Transformer replacement and maintenance,Cable and Fuse maintenance,Plant Shutdown,Inverter,Internet,Battery,Cloudy,Module Cleaning by rains,Grid Failure
7,2015-01-01 00:00:00,542,560,509.0,529.00,22.5,2162.5,2035.5,127,2197,2.78,77.02,Inverter No- 3 Auto trip 8:50 (modulre fan pro...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
8,2015-01-02 00:00:00,792,831,842.0,821.00,36.93,3322.93,3177,145.93,3352,4.15,78.72,Grid Failure From 13:02 to 13:09 WO#3402756,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
9,2006-01-03 00:00:00,933,978,995.0,953.00,49.96,3908.96,3755.25,153.71,3942,5.303,72.45,Grid Failure From 8:05 to 9:19 WO#3419549,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10,2015-01-04 00:00:00,1046,1102,1114.0,1071.00,61.29,4394.29,4210.5,183.79,4430,NaN,NaN,Grid Failure From 16:45 to 18:45 WO#3450753,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
11,2015-01-05 00:00:00,893,939,944.0,902.00,41.55,3719.55,3556.5,163.05,3744,4.8,76.02,The GERMI Plant has Failure The GRID From -1...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
12,2015-01-06 00:00:00,1040,1097,1102.0,1065.00,58.77,4362.77,4194,168.77,4388,5.726,74.69,Today I Replaced The D.C.12Amp Fuse Link of T...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
13,2015-01-07 00:00:00,543,571,577.0,551.00,29.48,2271.48,2167.5,103.98,3212,3.165,71.19,Grid Failure From 15:57 to 18:28 WO# 3518160,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
14,2015-01-08 00:00:00,1051,1113,1120.0,1077.00,60.24,4421.24,4242.75,178.49,4444,5.805,74.61,Grid Failure From 17:42 to 18:52 WO# 3545933,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
15,2015-01-09 00:00:00,1092,1154,1159.0,1150.00,66.91,4621.91,4439.25,182.66,4647,6.106,74.17,Battery water Fileed in 5 kw Battery Bank,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
16,2015-01-10 00:00:00,1079,1130,1130.0,1138.00,71.79,4548.79,4379.25,169.54,4580,6.021,74.13,Grid Failure From 13:48 to 13:57 WO# 3593881,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
17,2015-01-11 00:00:00,1091,1137,1154.0,1122.00,70.17,4574.17,4389.75,184.42,4592,6.051,73.96,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,2015-01-12 00:00:00,1041,1085,1124.0,1066.00,66.71,4382.71,4197,185.71,4398,6.031,71.07,Grid Failure From 14:48 to 15:08 WO#3648062 & ...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
19,2015-01-13 00:00:00,1034,1080,1126.0,1048.00,60.77,4348.77,4176.75,172.02,4401,5.773,74.3,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,2015-01-14 00:00:00,786,820,847.0,772.00,37.51,3262.51,3114,148.51,3290,4.273,75.04,Cloudy day & Inverer 4 run healthy but exhaust...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
21,2015-01-15 00:00:00,989,1023,1069.0,966.00,54.31,4101.31,3912.75,188.56,4110,5.362,74.7,Inverter no-4 run healthy but exhaust fan not ...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
22,2015-01-16 00:00:00,1040,1102,1119.0,1039.00,59.66,4359.66,4181.25,178.41,4379,5.738,74.38,Grid Failure From 11:05 to 11:08 WO#3758192,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
23,2015-01-17 00:00:00,1143,1193,1204.0,1113.00,66.42,4719.42,4523.25,196.17,4725,6.169,74.69,Grid Failure From 13:39 to 13:46 WO#3798043,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
24,2015-01-18 00:00:00,1192,1238,1238.0,1153.00,69.02,4890.02,4687.5,202.52,4901,6.416,74.45,NO any Issue,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,2015-01-19 00:00:00,1108,1142,1154.0,1072.00,63.1,4539.1,4354.5,184.6,4548,5.922,74.85,Transformer -1 & 4 (P.M),NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,2015-01-20 00:00:00,950,978,984.0,904.00,48.11,3864.11,3708.75,155.36,3872,5.094,74.08,NO any Issue,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,2015-01-21 00:00:00,509,515,520.0,506.00,19.88,2069.88,1950.75,119.13,2092,2.54,80.27,fully cloudy Day,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
28,2015-01-22 00:00:00,1131,1198,1215.0,1171.00,59.33,4774.33,4583,191.33,4797,6.087,76.81,NO any Issue,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,2015-01-23 00:00:00,1142,1205,1227.0,1171.00,69.43,4814.43,4617.75,196.68,4824,6.101,77.06,Today I Replaced The D.C.12Amp Fuse Link of T...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
30,2015-01-24 00:00:00,1012,1063,1080.0,1020.00,57.57,4232.57,4059,173.57,4271,5.268,78.97,Grid supply failure from 13:29 to 13:34(WO#402...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
31,2015-01-25 00:00:00,622,650,661.0,618.00,26.01,2577.01,2443.5,133.51,2621,3.217,79.4,NO any Issue,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,2015-01-26 00:00:00,1023,1074,1097.0,1010.00,52.93,4256.93,4077.75,179.18,4292,5.451,76.74,Grid supply failure from 17:22 to 17:55 (WO#),NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
33,2015-01-27 00:00:00,1159,1221,1238.0,1180.00,66.97,4864.97,4671.75,193.22,4875,6.162,77.1,NO any Issue,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34,2015-01-28 00:00:00,1255,1334,1362.0,1293.00,77.77,5321.77,5103,218.77,5320,NaN,NaN,Internet failure,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
35,2015-01-29 00:00:00,1211,1289,1312.0,1226.00,74.45,5112.45,4900.5,211.95,5102,6.498,76.52,Grid supply failure from 12:20 to 12:30 (WO#41...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
36,2015-01-30 00:00:00,1238,1329,1334.0,1267.00,76.26,5244.26,5031,213.26,5251,6.586,77.7,NO any Issue,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37,2015-01-31 00:00:00,1260,1334,1340.0,1386.00,76.27,5396.27,5086.5,309.77,5308,6.783,76.27,"Inverter no- 1,2,3,4, filter cleaning",NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39,2015-02-01 00:00:00,1148,1210,1221.0,1153.00,72.39,4804.39,4611,193.39,4805,6.005,77.98894,NO any Issue,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40,2015-02-02 00:00:00,1098,1153,1159.0,1115.00,65.25,4590.25,4403.25,187,4609,5.983,75.08,NO any Issue,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41,2015-02-03 00:00:00,735,775,775.0,766.00,30.54,3081.54,2947.5,134.04,3111,4.024,75.35,Grid supply failure from 9:55 to 12:38 (WO#437...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
42,2015-02-04 00:00:00,1227,1288,1317.0,1273.00,73.57,5178.57,4968,210.57,5207,6.545,77.54,"Module cleaning done Inverter 3 Row N,O,P,Q,R....",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43,2015-02-05 00:00:00,1102,1165,1204.0,1129.00,63.38,4663.38,4477.5,185.88,4683,5.798,78.72,"Module cleaning done Inverter 2 & 3 Row K,L,M....",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44,2015-02-06 00:00:00,1040,1125,1131.0,1049.00,60.32,4405.32,4227.75,177.57,4425,5.684,75.87,"Module cleaning done Inverter 2 Row I,J. Total...",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45,2015-02-07 00:00:00,1125,1198,1198.0,1129.00,66.99,4716.99,4522.5,194.49,4730,6.103,76.49,Module cleaning done Inverter 2 & 3 Row . Tota...,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
46,2015-02-08 00:00:00,1199,1272,1278.0,1196.00,72.62,5017.62,4812.75,204.87,5023,6.407,76.41,NO any Issue,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
47,2015-02-09 00:00:00,1261,1323,1323.0,1275.00,77.67,5259.67,5049,210.67,5267,6.666,77.01,"Module cleaning done Inverter 1 & 4 Row A,B.& ...",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48,2015-02-10 00:00:00,1147,1199,1204.0,1167.00,65.98,4782.98,4591.5,191.48,4797,6.018,77.69,"Module cleaning done Inverter 4 Row .& F,G,H,I...",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49,2015-02-11 00:00:00,1125,1187,1199.0,1172.00,66.17,4749.17,4563.75,185.42,4769,6.044,76.9,"Module cleaning done Inverter 4 & Trackers, Ro...",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50,2015-02-12 00:00:00,1244,1317,1357.0,1312.00,79.38,5309.38,5109.75,199.63,5328,6.699,77.51,"Module cleaning done Inverter 3 Row ,O,P,Q,R,...",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
51,2015-02-13 00:00:00,1219,1307,1345.0,1287.00,77.68,5235.68,5032.5,203.18,5248,6.674,76.64,"Module cleaning done Inverter 3 & 2 Row ,K,L,...",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,2015-02-14 00:00:00,1161,1249,1272.0,1208.00,72.81,4962.81,4760.25,202.56,4969,6.383,75.87,NO any Issue,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53,2015-02-15 00:00:00,1119,1198,1221.0,1169.00,69.15,4776.15,4593,183.15,4791,6.186,75.48,NO any Issue,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
54,2015-02-16 00:00:00,1199,1312,1312.0,1267.00,75.22,5165.22,4971,194.22,5207,6.606,76.82,"Module cleaning done Inverter 2 Row ,I,J Tota...",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
55,2015-02-17 00:00:00,1210,1323,1317.0,1260.00,76.37,5186.37,4988.25,198.12,5197,6.613,76.59,NO any Issue,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
56,2015-02-18 00:00:00,1102,1181,1176.0,1111.00,64.29,4634.29,4456.5,177.79,4652,6,75.56,Grid supply failure from 16:14 to 16:19 (WO#51...,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
57,2015-02-19 00:00:00,1125,1165,1159.0,1085.00,63.91,4597.91,4413.75,184.16,4634,5.931,76.15,"Module cleaning done Inverter -1 & 4 Row ,A,B...",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58,2015-02-20 00:00:00,1153,1199,1187.0,1170.00,65.8,4774.8,4594.5,180.3,4800,6.22,75.21,"Module cleaning done Inverter -4 Row -D,E,F,G,...",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
59,2015-02-21 00:00:00,1142,1181,1176.0,1205.00,67.7,4771.7,4587.75,183.95,4811,6.379,73.5,Grid Failure From - 13:10 to 13:13 (WO#5285421...,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
60,2015-02-22 00:00:00,864,933,921.0,937.00,43.45,3698.45,3587.25,111.2,3721,NaN,NaN,"Our side Grid Failure due to R' Y' B', D.O, fu...",NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
61,2015-02-23 00:00:00,1147,1193,1222.0,1209.00,66.41,4837.41,4649.25,188.16,4855,6.286,75.27,"Module cleaning done Inverter -4 Row -K,L, & T...",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
62,2015-02-24 00:00:00,973,1017,1068.0,1002.00,54.34,4114.34,3954.75,159.59,4163,5.179,78.34,"Module cleaning done Inverter-3 ROW- N,O,P,Q, ...",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
63,2015-02-25 00:00:00,1204,1306,1334.0,1260.00,74.06,5178.06,4966.5,211.56,5177,6.275,8041,"Module cleaning done Inverter-3 &2 ROW- J,K,L,...",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
64,2015-02-26 00:00:00,1312,1436,1431.0,1345.00,85.14,5609.14,5393.25,215.89,5605,6.926,78.87,"Module cleaning done Inverter- 2 & 1 ROW- G,H,...",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
65,2015-02-27 00:00:00,1277,1352,1334.0,1267.00,78.11,5308.11,5097.75,210.36,5340,6.89,75.53,"Module cleaning done Inverter- 1 ROW- A,B,C,D...",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
66,2015-02-28 00:00:00,1035,1073,1074.0,1002.00,56.6,4240.6,4071.75,168.85,4267,5.59,74.39,Today I Replaced The D.C.12Amp Fuse Link of Th...,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
68,2015-03-01 00:00:00,639,673,673.0,667.00,31.64,2683.64,2541,142.64,2706,3.361,78.47,Grid Failure From - 12:02 to 12:07 (WO#5787456...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
69,2015-03-02 00:00:00,1153,1221,1227.0,1206.00,63.95,4870.95,4676.25,194.7,4873,6.049,78.51,Today I Replaced The D.C.12Amp Fuse Link of Th...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
70,2015-03-03 00:00:00,1046,1114,1108.0,1092.00,62.6,4422.6,4241.25,181.35,4430,5.622,76.8,Today I Replaced The D.C.12Amp Fuse Link of Th...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
71,2015-03-04 00:00:00,1277,1357,1345.0,1375.00,80.68,5434.68,5217.75,216.93,5441,6.891,76.95,Grid supply failure from 15:10 to 15:15 (WO#60...,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
72,2015-03-05 00:00:00,1221,1300,1283.0,1302.00,74.51,5180.51,4977.75,202.76,5231,6.734,75.71,"Module cleaning done Inverter 4 Row ,F,G,H,I...",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
73,2015-03-06 00:00:00,1210,1284,1278.0,1301.00,73.53,5146.53,4943.25,203.28,5193,6.682,75.74,NO any Issue,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
74,2015-03-07 00:00:00,1086,1153,1165.0,1166.00,63.68,4633.68,4435.5,198.18,4671,6.051,75.23,"Module cleaning done Inverter 4 Row ,J,K,L, ...",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75,2015-03-08 00:00:00,1221,1306,1323.0,1340.00,79.43,5269.43,5061,208.43,5322,6.96,74.52,Grid supply failure from 16:58 to 17:15 (WO#63...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
76,2015-03-09 00:00:00,1306,1396,1430.0,1382.00,81.91,5595.91,5379,216.91,5603,7.172,76.14,"Module cleaning done Inverter 3 Row O,P,Q,R,S...",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
77,2015-03-10 00:00:00,1153,1250,1244.0,1211.00,66.54,4924.54,4725.75,198.79,4934,6.29,76.45,Grid supply Failure From - 9:45 to 9:47 & 9:59...,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
78,2015-03-11 00:00:00,1137,1232,1221.0,1184.00,63.96,4837.96,4653.75,184.21,4851,6.293,75.13,"Module cleaning done Inverter 2 Row H,I,J,K, ...",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
79,2015-03-12 00:00:00,1017,1080,1063.0,1011.00,50.99,4221.99,4044,177.99,4236,5.623,73.42,"Module cleaning done Inverter -1 Row D,E,F,G,...",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
80,2015-03-13 00:00:00,933,984,978.0,962.00,45.58,3902.58,3732.75,169.83,3945,5.085,75.61,"Module cleaning done Inverter 1 & 4 Row A,B,C...",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
81,2015-03-14 00:00:00,984,1034,1034.0,988.00,48.18,4088.18,3912.75,175.43,4124,5.318,75.58,Grid supply failure from 13:40 to 13:47 (WO#66...,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
82,2015-03-15 00:00:00,1221,1300,1295.0,1157.00,65.12,5038.12,4847.25,190.87,5084,6.704,73.91,Today I Replaced The D.C.12Amp Fuse Link of Th...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
83,2015-03-16 00:00:00,1351,1448,1441.0,1412.00,77.5,5729.5,5504.25,225.25,5727,7.375,75.68,Today I Replaced The D.C.12Amp Fuse Link of Th...,6812097,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
84,2015-03-17 00:00:00,1345,1436,1431.0,1441.00,78.4,5731.4,5505.75,225.65,5760,7.287,77.04,NO any Issue,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
85,2015-03-18 00:00:00,1380,1475,1475.0,1474.00,80.42,5884.42,5661,223.42,5918,7.515,76.75,"Module cleaning done Inverter-3 Row P,Q,R,S,T...",NaN,630,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
86,2015-03-19 00:00:00,1323,1425,1419.0,1408.00,77.55,5652.55,5451,201.55,5701,7.45,75.58,"Module cleaning done Inverter-3 & 2 Row L,M,N...",NaN,650,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
87,2015-03-20 00:00:00,1289,1391,1369.0,1382.00,73.98,5504.98,5292,212.98,5538,7.291,74.03,Today I Replaced The D.C.12Amp Fuse Link of Th...,7098699 7104864,650,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
88,2015-03-21 00:00:00,1130,1198,1159.0,1213.00,56.1,4756.1,4575,181.1,4801,7.105,65.85,Grid failure from - early morning to 9:26. Mod...,7165762,650,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
89,2015-03-22 00:00:00,1222,1295,1272.0,1303.00,61.11,5153.11,4953,200.11,5186,6.875,73.52,NO any Issue,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
90,2015-03-23 00:00:00,1238,1317,1294.0,1292.00,62.83,5203.83,5006.25,197.58,5242,7.116,71.79,"Module cleaning done Inverter-1 & 4 Row A,B,C...",7318204,640,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
91,2015-03-24 00:00:00,1255,1334,1317.0,1396.00,64.21,5366.21,5168.25,197.96,5385,7.155,73.35,"Module cleaning done Inverter-4 Row D,E,F,G, ...",NaN,660,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
92,2015-03-25 00:00:00,1164,1227,1233.0,1288.00,58.06,4970.06,4787.25,182.81,5014,6.696,72.98,"Module cleaning done Inverter-4 Row H,I,J,K,L...",NaN,720,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
93,2015-03-26 00:00:00,978,1035,1074.0,1062.00,44.13,4193.13,4023.75,169.38,4217,5.582,73.63,Today I Replaced The D.C.12Amp Fuse Link of Th...,7506678,630,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
94,2015-03-27 00:00:00,990,1079,1091.0,1058.00,47.59,4265.59,4097.25,168.34,4291,5.613,74.51,"Module cleaning done Inverter-3 & 2 Row L,M,N...",NaN,660,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
95,2015-03-28 00:00:00,1108,1199,1199.0,1182.00,53.72,4741.72,4569.75,171.97,4756,6.255,74.1,"Module cleaning done Inverter-1 & 2 Row ,H,I,...",NaN,670,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
96,2015-03-29 00:00:00,599,627,627.0,599.00,22.46,2474.46,2353.5,120.96,2512,3.007,81.42,Grid supply failure from 16:51 to 18:02 (WO#77...,7717067,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
97,2015-03-30 00:00:00,1323,1369,1402.0,1411.00,60.95,5565.95,5362.5,203.45,5613,7.373,74.19,"Module cleaning done Inverter-1 Row ,A,B,C,D,...",NaN,685,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
98,2015-03-31 00:00:00,1306,1373,1374.0,1411.00,60.49,5524.49,5325.75,198.74,5536,7.335,73.56,"Module cleaning done Inverter-4 Row ,A,B,C,D,...",7849439,630,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100,2015-04-01 00:00:00,1232,1295,1294.0,1337.00,57.1,5215.1,5001.75,213.35,NaN,NaN,NaN,"Module cleaning done Inverter-4 Row ,F,G,H,I,...",NaN,650,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101,2015-04-02 00:00:00,1187,1249,1250.0,1324.00,53.11,5063.11,4883.25,179.86,NaN,NaN,NaN,"Module cleaning done Inverter-4 Row ,J,K,L, &...",NaN,610,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
102,2015-04-03 00:00:00,1278,1346,1391.0,1433.00,61.73,5509.73,5315.25,194.48,5558,7.148,75.78,"Module cleaning done Inverter-3 Row P,Q,R,S,T ...",NaN,630,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
103,2015-04-04 00:00:00,848,882,938.0,893.00,37.29,3598.29,3458.25,140.04,3628,4.589,77.05,"Module cleaning done Inverter-2 & 3 Row L,M,N,...",817587,660,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [41]:
final_df = final_df.reset_index(drop=True)
final_df.dropna(subset=["Date"], inplace=True)
final_df.head(10)

,Date,1104500527,1104500529,1.104501e+09,7802195.0,2100570073/ 2100567820/ 2100567898,Total Generation (KWH),Aggregate Meter Reading (KWH),Difference,SEEDs data (KWH),Insolation,PR (%),Any Issues/Problems Observed,WO#,NO-OFF-CLEAN MODULES,Grid,Module Cleaning,Rainy day,No Module Cleaning,MCB Replacement,Inverter Maintenance,Transformer replacement and maintenance,Cable and Fuse maintenance,Plant Shutdown,Inverter,Internet,Battery,Cloudy,Module Cleaning by rains,Grid Failure
0,2015-01-01 00:00:00,542,560,509.0,529.0,22.5,2162.5,2035.5,127,2197,2.78,77.02,Inverter No- 3 Auto trip 8:50 (modulre fan pro...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,2015-01-02 00:00:00,792,831,842.0,821.0,36.93,3322.93,3177,145.93,3352,4.15,78.72,Grid Failure From 13:02 to 13:09 WO#3402756,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,2006-01-03 00:00:00,933,978,995.0,953.0,49.96,3908.96,3755.25,153.71,3942,5.303,72.45,Grid Failure From 8:05 to 9:19 WO#3419549,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,2015-01-04 00:00:00,1046,1102,1114.0,1071.0,61.29,4394.29,4210.5,183.79,4430,NaN,NaN,Grid Failure From 16:45 to 18:45 WO#3450753,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,2015-01-05 00:00:00,893,939,944.0,902.0,41.55,3719.55,3556.5,163.05,3744,4.8,76.02,The GERMI Plant has Failure The GRID From -1...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5,2015-01-06 00:00:00,1040,1097,1102.0,1065.0,58.77,4362.77,4194,168.77,4388,5.726,74.69,Today I Replaced The D.C.12Amp Fuse Link of T...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
6,2015-01-07 00:00:00,543,571,577.0,551.0,29.48,2271.48,2167.5,103.98,3212,3.165,71.19,Grid Failure From 15:57 to 18:28 WO# 3518160,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
7,2015-01-08 00:00:00,1051,1113,1120.0,1077.0,60.24,4421.24,4242.75,178.49,4444,5.805,74.61,Grid Failure From 17:42 to 18:52 WO# 3545933,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
8,2015-01-09 00:00:00,1092,1154,1159.0,1150.0,66.91,4621.91,4439.25,182.66,4647,6.106,74.17,Battery water Fileed in 5 kw Battery Bank,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
9,2015-01-10 00:00:00,1079,1130,1130.0,1138.0,71.79,4548.79,4379.25,169.54,4580,6.021,74.13,Grid Failure From 13:48 to 13:57 WO# 3593881,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [42]:
final_df.head(50)

,Date,1104500527,1104500529,1.104501e+09,7802195.0,2100570073/ 2100567820/ 2100567898,Total Generation (KWH),Aggregate Meter Reading (KWH),Difference,SEEDs data (KWH),Insolation,PR (%),Any Issues/Problems Observed,WO#,NO-OFF-CLEAN MODULES,Grid,Module Cleaning,Rainy day,No Module Cleaning,MCB Replacement,Inverter Maintenance,Transformer replacement and maintenance,Cable and Fuse maintenance,Plant Shutdown,Inverter,Internet,Battery,Cloudy,Module Cleaning by rains,Grid Failure
0,2015-01-01 00:00:00,542,560,509.0,529.0,22.5,2162.5,2035.5,127,2197,2.78,77.02,Inverter No- 3 Auto trip 8:50 (modulre fan pro...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,2015-01-02 00:00:00,792,831,842.0,821.0,36.93,3322.93,3177,145.93,3352,4.15,78.72,Grid Failure From 13:02 to 13:09 WO#3402756,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,2006-01-03 00:00:00,933,978,995.0,953.0,49.96,3908.96,3755.25,153.71,3942,5.303,72.45,Grid Failure From 8:05 to 9:19 WO#3419549,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,2015-01-04 00:00:00,1046,1102,1114.0,1071.0,61.29,4394.29,4210.5,183.79,4430,NaN,NaN,Grid Failure From 16:45 to 18:45 WO#3450753,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,2015-01-05 00:00:00,893,939,944.0,902.0,41.55,3719.55,3556.5,163.05,3744,4.8,76.02,The GERMI Plant has Failure The GRID From -1...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5,2015-01-06 00:00:00,1040,1097,1102.0,1065.0,58.77,4362.77,4194,168.77,4388,5.726,74.69,Today I Replaced The D.C.12Amp Fuse Link of T...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
6,2015-01-07 00:00:00,543,571,577.0,551.0,29.48,2271.48,2167.5,103.98,3212,3.165,71.19,Grid Failure From 15:57 to 18:28 WO# 3518160,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
7,2015-01-08 00:00:00,1051,1113,1120.0,1077.0,60.24,4421.24,4242.75,178.49,4444,5.805,74.61,Grid Failure From 17:42 to 18:52 WO# 3545933,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
8,2015-01-09 00:00:00,1092,1154,1159.0,1150.0,66.91,4621.91,4439.25,182.66,4647,6.106,74.17,Battery water Fileed in 5 kw Battery Bank,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
9,2015-01-10 00:00:00,1079,1130,1130.0,1138.0,71.79,4548.79,4379.25,169.54,4580,6.021,74.13,Grid Failure From 13:48 to 13:57 WO# 3593881,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10,2015-01-11 00:00:00,1091,1137,1154.0,1122.0,70.17,4574.17,4389.75,184.42,4592,6.051,73.96,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,2015-01-12 00:00:00,1041,1085,1124.0,1066.0,66.71,4382.71,4197,185.71,4398,6.031,71.07,Grid Failure From 14:48 to 15:08 WO#3648062 & ...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
12,2015-01-13 00:00:00,1034,1080,1126.0,1048.0,60.77,4348.77,4176.75,172.02,4401,5.773,74.3,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,2015-01-14 00:00:00,786,820,847.0,772.0,37.51,3262.51,3114,148.51,3290,4.273,75.04,Cloudy day & Inverer 4 run healthy but exhaust...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
14,2015-01-15 00:00:00,989,1023,1069.0,966.0,54.31,4101.31,3912.75,188.56,4110,5.362,74.7,Inverter no-4 run healthy but exhaust fan not ...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
15,2015-01-16 00:00:00,1040,1102,1119.0,1039.0,59.66,4359.66,4181.25,178.41,4379,5.738,74.38,Grid Failure From 11:05 to 11:08 WO#3758192,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
16,2015-01-17 00:00:00,1143,1193,1204.0,1113.0,66.42,4719.42,4523.25,196.17,4725,6.169,74.69,Grid Failure From 13:39 to 13:46 WO#3798043,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
17,2015-01-18 00:00:00,1192,1238,1238.0,1153.0,69.02,4890.02,4687.5,202.52,4901,6.416,74.45,NO any Issue,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,2015-01-19 00:00:00,1108,1142,1154.0,1072.0,63.1,4539.1,4354.5,184.6,4548,5.922,74.85,Transformer -1 & 4 (P.M),NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,2015-01-20 00:00:00,950,978,984.0,904.0,48.11,3864.11,3708.75,155.36,3872,5.094,74.08,NO any Issue,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,2015-01-21 00:00:00,509,515,520.0,506.0,19.88,2069.88,1950.75,119.13,2092,2.54,80.27,fully cloudy Day,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
21,2015-01-22 00:00:00,1131,1198,1215.0,1171.0,59.33,4774.33,4583,191.33,4797,6.087,76.81,NO any Issue,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,2015-01-23 00:00:00,1142,1205,1227.0,1171.0,69.43,4814.43,4617.75,196.68,4824,6.101,77.06,Today I Replaced The D.C.12Amp Fuse Link of T...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
23,2015-01-24 00:00:00,1012,1063,1080.0,1020.0,57.57,4232.57,4059,173.57,4271,5.268,78.97,Grid supply failure from 13:29 to 13:34(WO#402...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
24,2015-01-25 00:00:00,622,650,661.0,618.0,26.01,2577.01,2443.5,133.51,2621,3.217,79.4,NO any Issue,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,2015-01-26 00:00:00,1023,1074,1097.0,1010.0,52.93,4256.93,4077.75,179.18,4292,5.451,76.74,Grid supply failure from 17:22 to 17:55 (WO#),NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
26,2015-01-27 00:00:00,1159,1221,1238.0,1180.0,66.97,4864.97,4671.75,193.22,4875,6.162,77.1,NO any Issue,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,2015-01-28 00:00:00,1255,1334,1362.0,1293.0,77.77,5321.77,5103,218.77,5320,NaN,NaN,Internet failure,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
28,2015-01-29 00:00:00,1211,1289,1312.0,1226.0,74.45,5112.45,4900.5,211.95,5102,6.498,76.52,Grid supply failure from 12:20 to 12:30 (WO#41...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
29,2015-01-30 00:00:00,1238,1329,1334.0,1267.0,76.26,5244.26,5031,213.26,5251,6.586,77.7,NO any Issue,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,2015-01-31 00:00:00,1260,1334,1340.0,1386.0,76.27,5396.27,5086.5,309.77,5308,6.783,76.27,"Inverter no- 1,2,3,4, filter cleaning",NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
32,2015-02-01 00:00:00,1148,1210,1221.0,1153.0,72.39,4804.39,4611,193.39,4805,6.005,77.98894,NO any Issue,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,2015-02-02 00:00:00,1098,1153,1159.0,1115.0,65.25,4590.25,4403.25,187,4609,5.983,75.08,NO any Issue,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34,2015-02-03 00:00:00,735,775,775.0,766.0,30.54,3081.54,2947.5,134.04,3111,4.024,75.35,Grid supply failure from 9:55 to 12:38 (WO#437...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
35,2015-02-04 00:00:00,1227,1288,1317.0,1273.0,73.57,5178.57,4968,210.57,5207,6.545,77.54,"Module cleaning done Inverter 3 Row N,O,P,Q,R....",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36,2015-02-05 00:00:00,1102,1165,1204.0,1129.0,63.38,4663.38,4477.5,185.88,4683,5.798,78.72,"Module cleaning done Inverter 2 & 3 Row K,L,M....",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37,2015-02-06 00:00:00,1040,1125,1131.0,1049.0,60.32,4405.32,4227.75,177.57,4425,5.684,75.87,"Module cleaning done Inverter 2 Row I,J. Total...",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38,2015-02-07 00:00:00,1125,1198,1198.0,1129.0,66.99,4716.99,4522.5,194.49,4730,6.103,76.49,Module cleaning done Inverter 2 & 3 Row . Tota...,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
39,2015-02-08 00:00:00,1199,1272,1278.0,1196.0,72.62,5017.62,4812.75,204.87,5023,6.407,76.41,NO any Issue,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40,2015-02-09 00:00:00,1261,1323,1323.0,1275.0,77.67,5259.67,5049,210.67,5267,6.666,77.01,"Module cleaning done Inverter 1 & 4 Row A,B.& ...",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41,2015-02-10 00:00:00,1147,1199,1204.0,1167.0,65.98,4782.98,4591.5,191.48,4797,6.018,77.69,"Module cleaning done Inverter 4 Row .& F,G,H,I...",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42,2015-02-11 00:00:00,1125,1187,1199.0,1172.0,66.17,4749.17,4563.75,185.42,4769,6.044,76.9,"Module cleaning done Inverter 4 & Trackers, Ro...",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43,2015-02-12 00:00:00,1244,1317,1357.0,1312.0,79.38,5309.38,5109.75,199.63,5328,6.699,77.51,"Module cleaning done Inverter 3 Row ,O,P,Q,R,...",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44,2015-02-13 00:00:00,1219,1307,1345.0,1287.0,77.68,5235.68,5032.5,203.18,5248,6.674,76.64,"Module cleaning done Inverter 3 & 2 Row ,K,L,...",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45,2015-02-14 00:00:00,1161,1249,1272.0,1208.0,72.81,4962.81,4760.25,202.56,4969,6.383,75.87,NO any Issue,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46,2015-02-15 00:00:00,1119,1198,1221.0,1169.0,69.15,4776.15,4593,183.15,4791,6.186,75.48,NO any Issue,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
47,2015-02-16 00:00:00,1199,1312,1312.0,1267.0,75.22,5165.22,4971,194.22,5207,6.606,76.82,"Module cleaning done Inverter 2 Row ,I,J Tota...",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48,2015-02-17 00:00:00,1210,1323,1317.0,1260.0,76.37,5186.37,4988.25,198.12,5197,6.613,76.59,NO any Issue,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49,2015-02-18 00:00:00,1102,1181,1176.0,1111.0,64.29,4634.29,4456.5,177.79,4652,6,75.56,Grid supply failure from 16:14 to 16:19 (WO#51...,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
50,2015-02-19 00:00:00,1125,1165,1159.0,1085.0,63.91,4597.91,4413.75,184.16,4634,5.931,76.15,"Module cleaning done Inverter -1 & 4 Row ,A,B...",NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0